import React, { useEffect, useState } from "react";
import axios from "axios";
import { API_BASE_URL as APP_API_URL } from "../../config/api.js";
import { buyerHeaders } from "./buyerApi.js";
const API = `${APP_API_URL}/checklist`;
const blank = () => ({ taskDetails:"", status:"pending", dueDate:"" });
export default function CheckList() {
 const [items,setItems]=useState([]),[form,setForm]=useState(blank()),[editing,setEditing]=useState(null),[show,setShow]=useState(false),[error,setError]=useState("");
 const load=async()=>{try{const r=await axios.get(`${API}/`,{headers:buyerHeaders()});setItems(r.data||[]);setError("")}catch(e){setError(e.response?.data?.detail||"Could not load checklist.")}}; useEffect(()=>{load()},[]);
 const save=async()=>{if(!form.taskDetails.trim())return setError("Add a reminder.");try{if(editing)await axios.put(`${API}/${editing}`,form,{headers:buyerHeaders()});else await axios.post(`${API}/`,form,{headers:buyerHeaders()});setForm(blank());setEditing(null);setShow(false);load()}catch(e){setError(e.response?.data?.detail||"Could not save checklist item.")}};
 const toggle=async(item)=>{try{await axios.put(`${API}/${item.id}`,{...item,status:item.status==="completed"?"pending":"completed"},{headers:buyerHeaders()});load()}catch{setError("Could not update checklist.")}};
 const done=items.filter(x=>x.status==="completed").length;
 return <div className="buyer-work-page" style={{padding:24,fontFamily:"'Plus Jakarta Sans',sans-serif"}}><style>{`
  .buyer-work-page { max-width: 1320px; margin: 0 auto; }
  .buyer-work-page input:not([type="checkbox"]), .buyer-work-page select, .buyer-work-page textarea {
    border: 1px solid #D8E1EF; border-radius: 10px; padding: 10px 12px; color: #1E293B;
    font: 500 13px 'Plus Jakarta Sans', sans-serif; background: #fff; outline: none;
    transition: border-color .15s, box-shadow .15s;
  }
  .buyer-work-page input:focus, .buyer-work-page select:focus, .buyer-work-page textarea:focus { border-color:#6366F1; box-shadow:0 0 0 3px rgba(99,102,241,.12); }
  .buyer-work-page button { border: 1px solid #D8E1EF; border-radius: 9px; padding: 8px 12px; background:#fff; color:#334155; font:700 12px 'Plus Jakarta Sans', sans-serif; cursor:pointer; transition:transform .15s, box-shadow .15s, background .15s; }
  .buyer-work-page button:hover { transform:translateY(-1px); box-shadow:0 5px 12px rgba(15,23,42,.10); background:#F8FAFC; }
  .buyer-work-page button:active { transform:translateY(0); }
  .buyer-work-page input[type="checkbox"] { width:20px; height:20px; accent-color:#059669; cursor:pointer; }
  @media (max-width: 560px) { .buyer-work-page { padding: 4px !important; } .buyer-work-page h2 { font-size:21px !important; } }
`}</style><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",marginBottom:18}}><div><div style={{color:"#059669",fontSize:11,fontWeight:800,letterSpacing:".12em",textTransform:"uppercase"}}>Personal buyer reminders</div><h2 style={{margin:"5px 0",color:"#0F1B2D"}}>Checklist</h2><p style={{margin:0,color:"#64748B",fontSize:13}}>Optional reminders only. Checking one off does not approve a PO or change inventory.</p></div><button onClick={()=>{setEditing(null);setForm(blank());setShow(true)}} style={{border:0,borderRadius:10,padding:"10px 15px",background:"#059669",color:"#fff",fontWeight:800,cursor:"pointer"}}>+ Add reminder</button></div><div style={{marginBottom:16,padding:"12px 15px",borderRadius:13,background:"#ECFDF5",color:"#065F46",fontSize:13}}><b>{done}/{items.length}</b> reminders complete</div>{error&&<div style={{color:"#991B1B",marginBottom:10}}>{error}</div>}{show&&<div style={{padding:16,border:"1px solid #A7F3D0",borderRadius:14,marginBottom:16,background:"#F0FDF4"}}><input style={{width:"100%",boxSizing:"border-box",padding:10}} placeholder="e.g. Confirm vendor call before 4 PM" value={form.taskDetails} onChange={e=>setForm({...form,taskDetails:e.target.value})}/><div style={{display:"flex",gap:8,marginTop:10,flexWrap:"wrap"}}><input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/><button onClick={save}>Save reminder</button><button onClick={()=>setShow(false)}>Cancel</button></div></div>}<div style={{display:"grid",gap:8}}>{items.length===0?<div style={{padding:34,textAlign:"center",border:"1px dashed #CBD5E1",borderRadius:14,color:"#64748B"}}>No reminders. Keep this list short and personal.</div>:items.map(item=><div key={item.id} style={{display:"flex",alignItems:"center",gap:12,padding:14,border:"1px solid #E2E8F0",borderRadius:13,background:"#fff"}}><input type="checkbox" checked={item.status==="completed"} onChange={()=>toggle(item)}/><div style={{flex:1,textDecoration:item.status==="completed"?"line-through":"none",color:"#0F1B2D",fontWeight:600}}>{item.taskDetails}<div style={{fontSize:11,color:"#94A3B8",marginTop:3}}>{item.dueDate?`Reminder date: ${item.dueDate}`:"No date"}</div></div><button onClick={()=>{setEditing(item.id);setForm({taskDetails:item.taskDetails,status:item.status,dueDate:item.dueDate||""});setShow(true)}}>Edit</button><button onClick={async()=>{if(confirm("Delete this reminder?")){await axios.delete(`${API}/${item.id}`,{headers:buyerHeaders()});load()}}}>Delete</button></div>)}</div></div>;
}