import React, { useCallback, useEffect, useState } from "react";
import { BadgeIndianRupee, FileText, RefreshCw, Send, ShieldCheck } from "lucide-react";
import { API_BASE_URL } from "../../config/api.js";

const notesApi = `${API_BASE_URL}/mbuyer/debit-notes`;
const returnsApi = `${API_BASE_URL}/api/supplier-returns`;
const headers = () => ({ Authorization: `Bearer ${localStorage.getItem("admin_token") || localStorage.getItem("token") || ""}`, "Content-Type": "application/json" });
const money = (value) => `₹${Number(value || 0).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export default function Mbuyer1DebitNote() {
  const [returns, setReturns] = useState([]); const [notes, setNotes] = useState([]);
  const [sourceId, setSourceId] = useState(""); const [amount, setAmount] = useState(""); const [remarks, setRemarks] = useState("");
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { try { setLoading(true); const [r, n] = await Promise.all([fetch(`${returnsApi}/`, { headers: headers(), cache: "no-store" }), fetch(notesApi, { headers: headers(), cache: "no-store" })]); const [rd, nd] = await Promise.all([r.json(), n.json()]); if (!r.ok) throw new Error(rd.detail || "Could not load supplier returns."); if (!n.ok) throw new Error(nd.detail || "Could not load debit notes."); setReturns((rd.data || []).filter((row) => row.status === "Open" || row.status === "Closed")); setNotes(nd.data || []); } catch (e) { setError(e.message || "Could not load debit notes."); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const source = returns.find((row) => row.id === sourceId);
  const save = async () => { if (!source) return setError("Choose a Supplier Return Note first."); if (!(Number(amount) > 0)) return setError("Enter the debit amount to be reviewed."); try { setError(""); const response = await fetch(notesApi, { method: "POST", headers: headers(), body: JSON.stringify({ sourceType: "supplier_return", sourceId: source.id, sourceReference: source.srn_no, amount: Number(amount), remarks, originalInvoiceNo: source.po_no || "", receiverName: source.vendor_name || "", items: source.lines || [] }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || "Could not save debit note draft."); setMessage("Debit note draft saved. Finance must verify the return and post the accounting voucher."); setSourceId(""); setAmount(""); setRemarks(""); load(); } catch (e) { setError(e.message); } };
  return <div className="h-full overflow-y-auto bg-slate-50 p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-6xl space-y-5">
    <section className="rounded-3xl bg-gradient-to-br from-rose-950 via-red-900 to-orange-700 p-6 text-white shadow-xl"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-orange-200">Controlled finance workflow</p><h2 className="mt-2 text-2xl font-black">Debit Notes</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-orange-100">Raise a draft only against a real Supplier Return Note. It never changes stock or vendor balance by itself—Finance verifies it, then posts the final voucher.</p></div><button onClick={load} className="inline-flex items-center gap-2 rounded-xl bg-white/10 px-4 py-2 text-sm font-bold hover:bg-white/20"><RefreshCw className="h-4 w-4"/> Refresh</button></div></section>
    {message && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{message}</div>}{error && <div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm font-semibold text-rose-700">{error}</div>}
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex gap-3"><div className="rounded-xl bg-rose-100 p-3 text-rose-700"><BadgeIndianRupee className="h-5 w-5"/></div><div><h3 className="font-black text-slate-900">Create a linked debit-note draft</h3><p className="text-sm text-slate-500">Select the actual return. The value is capped by your internal finance review, not auto-posted.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2"><select value={sourceId} onChange={(e) => { setSourceId(e.target.value); if (!amount) setAmount(returns.find((r) => r.id === e.target.value)?.total_value || ""); }} className="rounded-xl border border-slate-200 px-3 py-3 text-sm font-semibold"><option value="">Select Supplier Return Note</option>{returns.map((row) => <option key={row.id} value={row.id}>{row.srn_no} · {row.vendor_name} · {money(row.total_value)}</option>)}</select><input value={amount} onChange={(e) => setAmount(e.target.value)} type="number" min="0" step="0.01" placeholder="Debit amount" className="rounded-xl border border-slate-200 px-3 py-3 text-sm"/></div><textarea value={remarks} onChange={(e) => setRemarks(e.target.value)} placeholder="Reason / Finance review note" className="mt-3 min-h-20 w-full rounded-xl border border-slate-200 p-3 text-sm"/><button onClick={save} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-rose-600 px-4 py-2.5 text-sm font-black text-white hover:bg-rose-700"><Send className="h-4 w-4"/> Save debit-note draft</button></section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-slate-100 p-5"><FileText className="h-5 w-5 text-rose-600"/><div><h3 className="font-black text-slate-900">Debit-note register</h3><p className="text-sm text-slate-500">Drafts remain traceable to their GRC return source.</p></div></div><div className="divide-y divide-slate-100">{notes.map((row) => <div key={row.id} className="flex flex-col gap-2 p-4 md:flex-row md:items-center md:justify-between"><div><div className="font-black text-slate-900">{row.sourceReference || row.serialNo || "Legacy debit note"}</div><p className="text-sm text-slate-500">{row.receiverName || "Vendor not recorded"} · {row.remarks || "No reason added"}</p></div><div className="flex items-center gap-2"><span className="font-black text-slate-900">{money(row.amount)}</span><span className="inline-flex items-center gap-1 rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-700"><ShieldCheck className="h-3.5 w-3.5"/>{row.status || "Draft"}</span></div></div>)}{!loading && !notes.length && <p className="p-6 text-sm text-slate-500">No debit-note drafts yet.</p>}</div></section>
  </div></div>;
}