import React, { useCallback, useEffect, useState } from "react";
import { API_BASE_URL } from "../../config/api.js";

const token = () => localStorage.getItem("vendor_token") || localStorage.getItem("access_token") || localStorage.getItem("token") || "";
async function api(path, options = {}) { const response = await fetch(`${API_BASE_URL}/api/vendor-b2b${path}`, { ...options, headers: { Authorization: `Bearer ${token()}`, "Content-Type": "application/json", ...(options.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.detail || "Request failed"); return data; }

export default function VendorB2BReturns({ orders = [] }) {
  const [returns, setReturns] = useState([]); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { const data = await api("/returns"); setReturns(data.data || []); } catch (err) { setError(err.message); } }, []); useEffect(() => { load(); }, [load]);
  const run = async (work, message) => { setSaving(true); setError(""); try { await work(); setNotice(message); await load(); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  const requestReturn = (order) => { const quantity = window.prompt(`Return quantity (received: ${order.received_quantity || 0} ${order.unit}):`); if (!quantity) return; const reason = window.prompt("Reason for return:"); if (!reason) return; run(() => api(`/orders/${order._id}/returns`, { method: "POST", body: JSON.stringify({ quantity, reason }) }), "Return request sent to supplier."); };
  const action = (ret, actionName) => { let body = { action: actionName }; if (actionName === "dispatch") { const expected = window.prompt("Expected delivery date (YYYY-MM-DD):"); if (!expected) return; body.expected_delivery_date = expected; body.transporter_name = window.prompt("Transporter (optional):") || ""; body.tracking_number = window.prompt("Tracking/AWB (optional):") || ""; } run(() => api(`/returns/${ret._id}/status`, { method: "PATCH", body: JSON.stringify(body) }), `Return ${actionName} completed.`); };
  return <section className="space-y-4"><div className="rounded-2xl border border-rose-100 bg-rose-50 p-4"><h2 className="font-black text-rose-950">B2B Returns & Credit Notes</h2><p className="mt-1 text-sm text-rose-800">Buyer requests a return after receiving goods. Supplier approves, buyer dispatches it, then supplier receives it. Receipt reverses the buyer’s B2B stock and issues a credit adjustment against the related B2B invoice.</p></div>{error && <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{notice && <p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}<div className="rounded-2xl border border-slate-200 bg-white p-4"><h3 className="font-black text-slate-900">Request a return</h3><div className="mt-3 flex flex-wrap gap-2">{orders.filter(o => o.viewer_role === "buying" && ["Received", "PartiallyReceived"].includes(o.status)).map(o => <button key={o._id} disabled={saving} onClick={() => requestReturn(o)} className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-700">Return {o.order_no}</button>)}{!orders.some(o => o.viewer_role === "buying" && ["Received", "PartiallyReceived"].includes(o.status)) && <p className="text-sm text-slate-500">No received B2B orders are eligible for return.</p>}</div></div>{returns.map(ret => <article key={ret._id} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-black text-slate-900">{ret.return_no} · {ret.title}</h3><p className="mt-1 text-sm text-slate-500">{ret.quantity} {ret.unit} · Credit {ret.currency} {ret.credit_amount}</p><p className="mt-1 text-xs text-slate-400">Reason: {ret.reason}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold text-slate-700">{ret.status}</span></div><div className="mt-3 flex flex-wrap gap-2">{ret.viewer_role === "selling" && ret.status === "Requested" && <><button disabled={saving} onClick={() => action(ret, "approve")} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Approve return</button><button disabled={saving} onClick={() => action(ret, "reject")} className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-700">Reject</button></>}{ret.viewer_role === "buying" && ret.status === "Approved" && <button disabled={saving} onClick={() => action(ret, "dispatch")} className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold text-white">Dispatch return</button>}{ret.viewer_role === "selling" && ret.status === "Dispatched" && <button disabled={saving} onClick={() => action(ret, "receive")} className="rounded-lg bg-amber-500 px-3 py-2 text-xs font-bold text-white">Receive return & issue credit</button>}</div></article>)}</section>;
}