import React, { useCallback, useEffect, useMemo, useState } from "react";
import { AlertCircle, ArrowDownToLine, BadgeIndianRupee, Building2, CalendarClock, ChartNoAxesCombined, CircleDollarSign, FileWarning, LockKeyhole, RefreshCw, Send, TrendingUp, WalletCards, X } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { API_BASE_URL } from "../../config/api.js";

const money = (value) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 }).format(Number(value) || 0);
const token = () => localStorage.getItem("vendor_token") || localStorage.getItem("access_token") || localStorage.getItem("token") || "";
const safeCsv = (value) => `"${String(value ?? "").replaceAll('"', '""')}"`;

function MetricCard({ icon: Icon, label, value, note, tone = "violet" }) {
  const tones = { violet: "bg-violet-50 text-violet-700 ring-violet-100", emerald: "bg-emerald-50 text-emerald-700 ring-emerald-100", amber: "bg-amber-50 text-amber-700 ring-amber-100", rose: "bg-rose-50 text-rose-700 ring-rose-100" };
  return <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className={`mb-3 flex h-10 w-10 items-center justify-center rounded-xl ring-1 ${tones[tone]}`}><Icon className="h-5 w-5" /></div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-xl font-black tracking-tight text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-500">{note}</p></article>;
}

function LockedFeature({ title, children }) {
  return <div className="flex min-h-44 flex-col items-center justify-center rounded-2xl border border-dashed border-violet-200 bg-violet-50/60 p-6 text-center"><span className="mb-3 grid h-10 w-10 place-items-center rounded-xl bg-white text-violet-600 shadow-sm"><LockKeyhole className="h-5 w-5" /></span><h3 className="text-sm font-black text-slate-900">{title}</h3><p className="mt-1 max-w-sm text-xs leading-5 text-slate-500">{children}</p></div>;
}

export default function VendorAnalytics() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [dispute, setDispute] = useState(null);
  const [description, setDescription] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [notice, setNotice] = useState("");

  const load = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const response = await fetch(`${API_BASE_URL}/api/vendor-finance/analytics`, { headers: { Authorization: `Bearer ${token()}` }, cache: "no-store" });
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.detail || "Finance data could not be loaded.");
      setData(payload);
    } catch (err) { setError(err.message || "Finance data could not be loaded."); }
    finally { setLoading(false); }
  }, []);

  useEffect(() => { load(); }, [load]);

  const exportTransactions = () => {
    if (!data?.access?.finance_export) return;
    const header = ["Date", "Invoice", "Retailer", "Mode", "Reference", "Amount"];
    const rows = (data.transactions || []).map((row) => [row.payment_date, row.invoice_no, row.retailer_name, row.payment_mode, row.reference_no, row.amount]);
    const csv = [header, ...rows].map((row) => row.map(safeCsv).join(",")).join("\n");
    const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }));
    const anchor = document.createElement("a"); anchor.href = url; anchor.download = `vendor-transactions-${new Date().toISOString().slice(0, 10)}.csv`; anchor.click(); URL.revokeObjectURL(url);
  };

  const submitDispute = async () => {
    if (!dispute || description.trim().length < 10) return;
    setSubmitting(true); setNotice("");
    try {
      const response = await fetch(`${API_BASE_URL}/api/vendor-finance/transactions/${dispute.invoice_id}/${dispute.payment_id}/dispute`, { method: "POST", headers: { Authorization: `Bearer ${token()}`, "Content-Type": "application/json" }, body: JSON.stringify({ description: description.trim() }) });
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.detail || "Issue could not be submitted.");
      setDispute(null); setDescription(""); setNotice(payload.message);
    } catch (err) { setNotice(err.message || "Issue could not be submitted."); }
    finally { setSubmitting(false); }
  };

  const summary = data?.summary || {};
  const overdueRate = useMemo(() => { const outstanding = Number(summary.outstanding) || 0; return outstanding ? Math.round(((Number(summary.overdue) || 0) / outstanding) * 100) : 0; }, [summary]);
  if (loading) return <div className="grid min-h-80 place-items-center"><RefreshCw className="h-7 w-7 animate-spin text-violet-600" /></div>;
  if (error) return <div className="mx-auto max-w-xl rounded-2xl border border-rose-200 bg-rose-50 p-6 text-center"><AlertCircle className="mx-auto h-7 w-7 text-rose-600" /><p className="mt-2 text-sm font-bold text-rose-800">{error}</p><button onClick={load} className="mt-4 rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white">Try again</button></div>;

  return <div className="min-h-full bg-slate-50/60 p-3 sm:p-5"><div className="mx-auto max-w-7xl space-y-5">
    <section className="overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-indigo-950 to-violet-900 p-5 text-white shadow-xl sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-[11px] font-bold uppercase tracking-widest ring-1 ring-white/15"><ChartNoAxesCombined className="h-3.5 w-3.5" /> Finance workspace</span><h2 className="mt-4 text-2xl font-black tracking-tight sm:text-3xl">Analytics & Finance</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-indigo-100">Track invoices, retailer-recorded receipts and automatically calculated outstanding balances.</p></div><div className="flex items-center gap-3"><span className="rounded-xl bg-white/10 px-4 py-2 text-xs font-bold ring-1 ring-white/15">{data.access.label} plan</span><button onClick={load} className="grid h-10 w-10 place-items-center rounded-xl bg-white text-slate-900 shadow-lg" title="Refresh"><RefreshCw className="h-4 w-4" /></button></div></div></section>
    {notice && <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs font-bold text-emerald-800">{notice}</div>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={BadgeIndianRupee} label="Total invoiced" value={money(summary.invoiced)} note={`${summary.invoice_count || 0} purchase invoices`} /><MetricCard icon={CircleDollarSign} label="Payments received" value={money(summary.paid)} note="Recorded by retailer accounts" tone="emerald" /><MetricCard icon={WalletCards} label="Outstanding" value={money(summary.outstanding)} note="Calculated from open invoices" tone="amber" /><MetricCard icon={CalendarClock} label="Overdue" value={money(summary.overdue)} note={`${summary.overdue_count || 0} invoices · ${overdueRate}% of outstanding`} tone="rose" /></section>
    <section className="grid gap-5 xl:grid-cols-[1.55fr_1fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-start justify-between gap-3"><div><h3 className="text-base font-black text-slate-900">Payment trend</h3><p className="mt-1 text-xs text-slate-500">Last {data.access.finance_history_months} months of recorded receipts</p></div><TrendingUp className="h-5 w-5 text-emerald-500" /></div><div className="h-64 w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.monthly_receipts || []} margin={{ left: 0, right: 8, top: 8, bottom: 0 }}><defs><linearGradient id="receiptFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#7c3aed" stopOpacity={0.35} /><stop offset="100%" stopColor="#7c3aed" stopOpacity={0.02} /></linearGradient></defs><CartesianGrid strokeDasharray="4 4" vertical={false} stroke="#e2e8f0" /><XAxis dataKey="month" tick={{ fontSize: 10, fill: "#64748b" }} axisLine={false} tickLine={false} /><YAxis tick={{ fontSize: 10, fill: "#64748b" }} axisLine={false} tickLine={false} tickFormatter={(v) => `₹${Math.round(v / 1000)}k`} /><Tooltip formatter={(value) => [money(value), "Received"]} contentStyle={{ borderRadius: 12, borderColor: "#e2e8f0", fontSize: 12 }} /><Area type="monotone" dataKey="received" stroke="#7c3aed" strokeWidth={3} fill="url(#receiptFill)" /></AreaChart></ResponsiveContainer></div></div>
      {data.access.finance_forecasting ? <div className="rounded-2xl border border-indigo-200 bg-gradient-to-br from-indigo-50 to-violet-50 p-5 shadow-sm"><span className="grid h-11 w-11 place-items-center rounded-xl bg-white text-violet-700 shadow-sm"><TrendingUp className="h-5 w-5" /></span><p className="mt-5 text-xs font-bold uppercase tracking-wider text-violet-600">Next-month estimate</p><p className="mt-2 text-3xl font-black text-slate-950">{money(data.forecast_next_month_receipts)}</p><p className="mt-3 text-xs leading-5 text-slate-600">A simple planning estimate based on your latest three months. It is not a guaranteed collection amount.</p></div> : <LockedFeature title="Receipt forecasting is Premium">Upgrade to Premium to see a next-month receipt estimate from recent payment history.</LockedFeature>}
    </section>
    <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="text-base font-black text-slate-900">Payment transactions</h3><p className="mt-1 text-xs text-slate-500">Read-only receipts entered by retailer accounts · latest {data.access.finance_transaction_limit}</p></div><button disabled={!data.access.finance_export} onClick={exportTransactions} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-xs font-bold text-slate-700 disabled:cursor-not-allowed disabled:opacity-40">{data.access.finance_export ? <ArrowDownToLine className="h-4 w-4" /> : <LockKeyhole className="h-4 w-4" />}Export CSV</button></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-xs"><thead className="bg-slate-50 text-[10px] font-black uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Date</th><th className="px-4 py-3">Invoice</th><th className="px-4 py-3">Retailer</th><th className="px-4 py-3">Method</th><th className="px-4 py-3">Reference</th><th className="px-4 py-3 text-right">Amount</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{(data.transactions || []).map((row) => <tr key={`${row.invoice_id}-${row.payment_id}`} className="hover:bg-slate-50/70"><td className="px-5 py-4 text-slate-600">{row.payment_date || "—"}</td><td className="px-4 py-4 font-bold text-slate-900">{row.invoice_no || "—"}</td><td className="px-4 py-4 text-slate-700">{row.retailer_name}</td><td className="px-4 py-4"><span className="rounded-lg bg-slate-100 px-2 py-1 font-bold text-slate-600">{row.payment_mode || "Other"}</span></td><td className="px-4 py-4 text-slate-500">{row.reference_no || "—"}</td><td className="px-4 py-4 text-right font-black text-emerald-700">{money(row.amount)}</td><td className="px-5 py-4 text-right"><button onClick={() => { setDispute(row); setDescription(""); setNotice(""); }} className="font-bold text-violet-700 hover:text-violet-900">Report issue</button></td></tr>)}</tbody></table>{!data.transactions?.length && <div className="p-10 text-center text-sm text-slate-400">No payment transactions have been recorded yet.</div>}</div></section>
    <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h3 className="text-base font-black text-slate-900">Outstanding invoices</h3><p className="mt-1 text-xs text-slate-500">Created automatically from invoice total minus retailer-recorded payments; vendors cannot manually create balances.</p></div><div className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-3">{(data.outstanding_invoices || []).map((invoice) => <article key={invoice.invoice_id} className={`rounded-xl border p-4 ${invoice.overdue ? "border-rose-200 bg-rose-50/60" : "border-slate-200 bg-slate-50/60"}`}><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-black text-slate-900">{invoice.invoice_no || "Invoice"}</p><p className="mt-1 flex items-center gap-1 text-xs text-slate-500"><Building2 className="h-3 w-3" />{invoice.retailer_name}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-black ${invoice.overdue ? "bg-rose-100 text-rose-700" : "bg-amber-100 text-amber-700"}`}>{invoice.overdue ? "Overdue" : invoice.payment_status}</span></div><p className="mt-4 text-xs text-slate-500">Balance due</p><p className="text-lg font-black text-slate-950">{money(invoice.balance_due)}</p><p className="mt-2 text-[11px] text-slate-500">Due {invoice.due_date || "date not provided"}</p></article>)}{!data.outstanding_invoices?.length && <div className="col-span-full p-8 text-center text-sm text-slate-400">No outstanding invoices. You are all settled.</div>}</div></section>
    {data.access.finance_retailer_breakdown ? <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="text-base font-black text-slate-900">Retailer account breakdown</h3><p className="mt-1 text-xs text-slate-500">Compare billed, received and outstanding value by retailer.</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{(data.retailer_breakdown || []).map((row) => <article key={row.tenant_id} className="rounded-xl border border-slate-200 p-4"><p className="truncate text-sm font-black text-slate-900">{row.retailer_name}</p><div className="mt-3 grid grid-cols-3 gap-2 text-[10px] text-slate-500"><div>Billed<strong className="mt-1 block text-xs text-slate-900">{money(row.invoiced)}</strong></div><div>Received<strong className="mt-1 block text-xs text-emerald-700">{money(row.paid)}</strong></div><div>Due<strong className="mt-1 block text-xs text-amber-700">{money(row.outstanding)}</strong></div></div></article>)}</div></section> : <LockedFeature title="Retailer breakdown starts with Standard">Upgrade to compare invoiced, received and outstanding amounts retailer by retailer.</LockedFeature>}
  </div>
  {dispute && <div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/60 p-4 backdrop-blur-sm" onMouseDown={(e) => { if (e.target === e.currentTarget) setDispute(null); }}><div className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl"><div className="flex items-start justify-between"><div><span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-50 text-amber-700"><FileWarning className="h-5 w-5" /></span><h3 className="mt-3 text-lg font-black text-slate-900">Report a payment issue</h3><p className="mt-1 text-xs text-slate-500">{dispute.invoice_no} · {money(dispute.amount)} · {dispute.reference_no || "No reference"}</p></div><button onClick={() => setDispute(null)} className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100 text-slate-500"><X className="h-4 w-4" /></button></div><div className="mt-4 rounded-xl bg-indigo-50 p-3 text-xs leading-5 text-indigo-800">Payment records are controlled by the retailer accounts team. Your report is attached to this invoice so they can verify and correct it.</div><label className="mt-4 block text-xs font-bold text-slate-700">What is incorrect?</label><textarea value={description} onChange={(e) => setDescription(e.target.value)} rows={5} maxLength={1000} placeholder="Example: This payment reference belongs to another invoice..." className="mt-2 w-full resize-none rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:border-violet-400 focus:ring-4 focus:ring-violet-100" /><button disabled={submitting || description.trim().length < 10} onClick={submitDispute} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-violet-700 px-4 py-3 text-sm font-black text-white disabled:opacity-40"><Send className="h-4 w-4" />{submitting ? "Submitting..." : "Send to retailer accounts"}</button></div></div>}
  </div>;
}
