import React, { useCallback, useEffect, useMemo, useState } from "react";
import { AlertCircle, BookOpen, CheckCircle2, ClipboardCheck, Factory, FileText, Gauge, LayoutDashboard, MessageSquare, Palette, Plus, RefreshCw, Ruler, Search, Send, Settings, X } from "lucide-react";
import { API_BASE_URL } from "../config/api.js";
import { logoutOrReturnToDepartmentSelector, getAdminName, getAdminScope, getStoreName } from "../utils/authRedirect.js";
import TechPackLibrary from "./Production/TechPackLibrary.jsx";
import AdminSettings from "./Admin/AdminSettings.jsx";

const TABS = [
  ["dashboard", "Dashboard", LayoutDashboard], ["research", "Research & Mood Boards", Search], ["projects", "Design Projects", Palette], ["patterns", "Patterns", Ruler],
  ["artwork", "Print & Artwork", FileText], ["samples", "Samples & Approval", ClipboardCheck], ["techpacks", "Tech Packs", BookOpen], ["handoff", "Production Handoff", Factory],
  ["floorops", "Daily Floor Log", Gauge],
  ["queries", "Queries", MessageSquare], ["changes", "Change Control", AlertCircle], ["reports", "Reports", CheckCircle2],
];
const GUIDES={
dashboard:["Review live counts and Production Readiness.","Open the tab connected to any missing item.","Next: start Research or create a Design Project."],
research:["Add season, market, department, tags and findings.","Attach source, image and document links.","Next: turn the approved direction into a Design Project."],
projects:["Create one master project per style and keep its design number unchanged.","Set owner, priority, quantity, cost and launch date; update status as work progresses.","Next: add the first Pattern Version."],
patterns:["Choose the project; record base size, sizes, width, consumption and wastage.","Enter grading as Point | Base | S:value,M:value and upload CAD/DXF/PDF files.","Use Create Revision for V2/V3. Next: develop artwork and sample."],
artwork:["Link the print/embroidery to a project.","Record version, dimensions, placement, technique, colours and file links.","Next: validate it on a sample and include the approved version in the Tech Pack."],
samples:["Choose project, pattern, sample type, assignee, materials, cost and due date.","On receipt, record fit/construction results and the decision.","Approved continues to Tech Pack; Revision/Resample returns to Pattern or Artwork."],
techpacks:["Use the exact Design Project number.","Complete Sketch, Spec Sheet, Details, Artwork, Trims/Labels and Colourways; upload references.","Download/review the PDF. Use a new version for major changes. Next: Handoff."],
handoff:["Confirm approved sample and matching Tech Pack.","Record Design Head approval; Production separately records feasibility.","Choose an existing BOM or auto-create one from pattern consumption, then Release to Production."],
floorops:["Floor workers have no login — a supervisor logs each entry on their behalf; pick a name or type one for a walk-in.","Choose the department first; the form only shows the fields that department needs (set these up under Settings).","Switch to KPI Summary for efficiency, rework, rejection and on-time % by department, worker or style."],
queries:["Select the affected design, category and priority.","Describe one clear technical issue; Design and Production share the same feed.","Resolve with a written answer. Use Change Control if released instructions change."],
changes:["Record reason, previous spec, new spec, and material/cost/delivery impact.","The system identifies affected open job orders.","Production accepts/rejects and acknowledges; accepted changes require a new controlled version."],
reports:["Review release rate, sample cost and revisions.","Balance work using Designer Workload and Deadline Calendar.","Compare target, BOM material and sample cost with matched sales units."]
};
const SUBTITLES = {
  dashboard: "Live status across the design-to-production pipeline.",
  research: "Season, market and trend references for design projects.",
  projects: "One traceable record per style, from idea to production release.",
  patterns: "Controlled pattern, grading and consumption versions.",
  artwork: "Versioned print, embroidery and placement references.",
  samples: "Every sample round and the decision that gates Production.",
  techpacks: "The locked technical reference shared with Production.",
  handoff: "Approvals, feasibility and release to Production.",
  floorops: "Daily shop-floor entries and KPIs — Pattern, Layering, Cutting, Stitching, Embroidery and more.",
  queries: "Technical clarifications shared with Production.",
  changes: "Post-release specification changes and their impact.",
  reports: "Workload, deadlines, cost and sales performance.",
  settings: "Department lists and form defaults used across this workspace.",
};
const DP_UI_STYLES = `
  .dp-workspace { min-height: 100vh; color: #17213a; background: radial-gradient(circle at 88% -8%, rgba(217,70,239,.14), transparent 32rem), radial-gradient(circle at 28% 0%, rgba(139,92,246,.10), transparent 30rem), #f7f6fb; }
  .dp-workspace .dp-sidebar { width: 280px; background: linear-gradient(165deg, #2a0f37 0%, #4c1d6b 48%, #a21caf 150%); box-shadow: 14px 0 40px rgba(15,23,42,.10); }
  .dp-workspace .dp-brand { border: 1px solid rgba(255,255,255,.13); background: rgba(255,255,255,.065); }
  .dp-workspace .dp-nav-item { color: #f0d9ff; border: 1px solid transparent; }
  .dp-workspace .dp-nav-item:hover { background: rgba(255,255,255,.08); color: #fff; }
  .dp-workspace .dp-nav-item-active { color: #fff; border-color: rgba(240,171,252,.25); background: linear-gradient(90deg, rgba(168,85,247,.36), rgba(236,72,153,.26)); box-shadow: 0 8px 18px rgba(2,6,23,.18); }
  .dp-workspace .dp-content { min-width: 0; }
  .dp-workspace .dp-header { background: rgba(255,255,255,.86); border-bottom: 1px solid #ece7f2; backdrop-filter: blur(14px); }
  @media (max-width: 1000px) { .dp-workspace .dp-sidebar { width: 74px; } .dp-workspace .dp-brand-copy, .dp-workspace .dp-nav-label, .dp-workspace .dp-sidebar-note { display: none; } .dp-workspace .dp-nav-item { justify-content: center; padding-left: 0; padding-right: 0; } .dp-workspace .dp-nav-item svg { margin-right: 0; } }
`;
const DEPARTMENTS = ["Men", "Women", "Kids Boys", "Kids Girls", "Infant", "Accessories", "Other"];
const DEFAULT_SETTINGS = { departments: DEPARTMENTS, sample_types: ["Proto sample", "Development sample", "Fit sample", "Size-set sample", "Print / embroidery sample", "Wash sample", "Pre-production sample", "Production sample"], default_base_size: "M", default_size_run: "S, M, L, XL", default_wastage_pct: 5 };
const PROJECT_STATUSES = ["IDEA", "IN_DEVELOPMENT", "PATTERN_DEVELOPMENT", "SAMPLE_DEVELOPMENT", "REVISION_REQUIRED", "AWAITING_APPROVAL", "APPROVED_FOR_PRODUCTION", "ON_HOLD", "REJECTED", "ARCHIVED"];
const SAMPLE_TYPES = ["Proto sample", "Development sample", "Fit sample", "Size-set sample", "Print / embroidery sample", "Wash sample", "Pre-production sample", "Production sample"];
const DECISIONS = ["PENDING", "APPROVED", "APPROVED_WITH_COMMENTS", "REVISION_REQUIRED", "REJECTED", "RESAMPLE_REQUIRED"];
const emptyProject = { design_no:"", style_name:"", department:"Women", category:"", theme:"", collection:"", season:"", designer:"", target_customer:"", target_cost:"", planned_quantity:"", launch_date:"", priority:"MEDIUM", description:"", moodboard_urls:"", document_urls:"" };
const emptyPattern = { project_id:"", pattern_no:"", pattern_name:"", version:"v1", base_size:"M", sizes:"S, M, L, XL", fabric_width:"", consumption_per_unit:"", wastage_pct:"5", marker_length:"", marker_efficiency:"", seam_allowance:"", shrinkage_allowance:"", measurement_rows:"", file_urls:"", notes:"" };
const emptySample = { project_id:"", pattern_id:"", sample_type:"Development sample", quantity:"1", required_date:"", received_date:"", assigned_to:"", estimated_cost:"", actual_cost:"", materials:"", image_urls:"", decision:"PENDING", fit_result:"", construction_result:"", review_notes:"" };
const emptyQuery = { project_id:"", category:"Measurement clarification", description:"", priority:"MEDIUM", attachment_urls:"" };
const emptyResearch = { title:"", category:"Fashion trend", season:"", department:"Women", market_segment:"", tags:"", reference_urls:"", notes:"" };
const emptyArtwork = { project_id:"", name:"", kind:"Print", version:"v1", width:"", height:"", placement:"", technique:"", colours:"", file_urls:"", notes:"", status:"DRAFT" };
const emptyChange = { project_id:"", reason:"", previous_spec:"", new_spec:"", material_impact:"", cost_impact:"", delivery_impact:"", before_urls:"", after_urls:"" };

// ── Daily shop-floor KPI logging ──────────────────────────────────────────
// Floor workers have no login; a supervisor fills this on their behalf. One
// form adapts its fields per department instead of a hardcoded form each.
const DEFAULT_FLOOR_DEPARTMENTS = [
  { name:"Pattern Making", fields:["target_qty","completed_qty","rework_qty","on_time","remarks"], labels:{target_qty:"Target patterns",completed_qty:"Completed patterns",rework_qty:"Rework qty"} },
  { name:"Layering", fields:["fabric_used_mtrs","wastage_mtrs","vendor_name","on_time","remarks"], labels:{fabric_used_mtrs:"Fabric used (mtrs)",wastage_mtrs:"Wastage (mtrs)",vendor_name:"Vendor (fabric source)"} },
  { name:"Cutting", fields:["fabric_used_mtrs","vendor_name","target_qty","completed_qty","rejected_qty","wastage_mtrs","on_time","remarks"], labels:{target_qty:"Target pcs",completed_qty:"Cut pcs",rejected_qty:"Rejected pcs",fabric_used_mtrs:"Fabric used (mtrs)",wastage_mtrs:"Wastage (mtrs)",vendor_name:"Vendor (fabric source)"} },
  { name:"Stitching", fields:["target_qty","completed_qty","rework_qty","rejected_qty","on_time","remarks"], labels:{target_qty:"Target pcs",completed_qty:"Stitched pcs",rework_qty:"Rework pcs",rejected_qty:"Rejected pcs"} },
  { name:"Embroidery", fields:["target_qty","completed_qty","rejected_qty","on_time","remarks"], labels:{target_qty:"Target pcs",completed_qty:"Embroidered pcs",rejected_qty:"Rejected pcs"} },
];
const FLOOR_FIELD_META = {
  target_qty:{label:"Target qty",type:"number"}, completed_qty:{label:"Completed qty",type:"number"},
  rework_qty:{label:"Rework qty",type:"number"}, rejected_qty:{label:"Rejected qty",type:"number"},
  fabric_used_mtrs:{label:"Fabric used (mtrs)",type:"number"}, wastage_mtrs:{label:"Wastage (mtrs)",type:"number"},
  vendor_name:{label:"Vendor (fabric source)",type:"text"}, on_time:{label:"On time",type:"bool"}, remarks:{label:"Remarks",type:"text"},
};
const todayISO = () => new Date().toISOString().slice(0,10);
const emptyFloorLog = () => ({ date:todayISO(), time:"", department:"", worker_id:"", worker_name:"", design_no:"", vendor_name:"", job_work_order_id:"", target_qty:"", completed_qty:"", rework_qty:"", rejected_qty:"", fabric_used_mtrs:"", wastage_mtrs:"", on_time:true, remarks:"" });
const emptyFloorWorker = { name:"", phone:"", departments:[], notes:"" };

function headers(){ const token=localStorage.getItem("admin_token")||localStorage.getItem("access_token")||localStorage.getItem("token")||""; return {"Content-Type":"application/json", ...(token?{Authorization:`Bearer ${token}`}:{})}; }
async function api(path, options={}){ const response=await fetch(`${API_BASE_URL}/api/design-pattern${path}`,{...options,headers:{...headers(),...(options.headers||{})}}); const data=await response.json().catch(()=>({})); if(!response.ok) throw new Error(data.detail||"Unable to complete this action."); return data; }
const gradingRows=(text)=>String(text||"").split("\n").map(line=>{const [point,base,raw=""]=line.split("|");return {point:point?.trim(),base_value:base?.trim(),grades:Object.fromEntries(raw.split(",").map(x=>x.split(":").map(v=>v.trim())).filter(x=>x[0]))};}).filter(x=>x.point);
const pretty=(value)=>String(value||"").replaceAll("_"," ").toLowerCase().replace(/\b\w/g,(c)=>c.toUpperCase());
const tone=(status)=> status?.includes("APPROVED")||status?.includes("RELEASED")||status==="RESOLVED"||status==="CLOSED" ? "bg-emerald-50 text-emerald-700 ring-emerald-200" : status?.includes("REVISION")||status==="REJECTED" ? "bg-rose-50 text-rose-700 ring-rose-200" : status?.includes("AWAITING")||status==="PENDING" ? "bg-amber-50 text-amber-700 ring-amber-200" : "bg-violet-50 text-violet-700 ring-violet-200";
function Badge({value}){ return <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-bold ring-1 ${tone(value)}`}>{pretty(value)}</span>; }
function Field({label,children,wide=false}){ return <label className={wide?"md:col-span-2":""}><span className="mb-1.5 block text-xs font-black uppercase tracking-wide text-slate-500">{label}</span>{React.cloneElement(children,{className:`w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100 ${children.props.className||""}`})}</label>; }
function Modal({title,onClose,children}){ return <div className="fixed inset-0 z-[1000] grid place-items-center bg-slate-950/55 p-3 backdrop-blur-sm"><section className="max-h-[94vh] w-full max-w-3xl overflow-x-hidden overflow-y-auto rounded-3xl bg-white shadow-2xl"><header className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-6 py-4"><h2 className="text-xl font-black text-slate-900">{title}</h2><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-xl border"><X className="h-4 w-4"/></button></header>{children}</section></div>; }
function Empty({children}){ return <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-10 text-center text-sm text-slate-500">{children}</div>; }
function AttachmentGallery({urls=[],label="Attachment"}){const list=(urls||[]).filter(Boolean);if(!list.length)return null;return <div className="flex max-w-full flex-wrap gap-2">{list.slice(0,8).map((url,index)=><a key={`${url}-${index}`} href={url} target="_blank" rel="noreferrer" title={`Open ${label}`} className="group relative h-16 w-16 overflow-hidden rounded-xl border border-slate-200 bg-slate-100"><img src={url} alt={`${label} ${index+1}`} className="h-full w-full object-cover" onError={e=>{e.currentTarget.style.display="none";e.currentTarget.nextSibling.style.display="grid";}}/><span style={{display:"none"}} className="h-full w-full place-items-center p-1 text-center text-[9px] font-bold text-violet-700">Open file</span></a>)}</div>}
function AttachmentEditor({label,value,onChange,accept="image/*"}){const urls=String(value||"").split("\n").map(x=>x.trim()).filter(Boolean);const add=added=>onChange([...urls,...added].join("\n"));const remove=index=>onChange(urls.filter((_,i)=>i!==index).join("\n"));return <div className="md:col-span-2 space-y-2"><AssetUploader label={label} accept={accept} onUploaded={add}/>{urls.length>0&&<div className="flex flex-wrap gap-2">{urls.map((url,index)=><div key={`${url}-${index}`} className="relative"><a href={url} target="_blank" rel="noreferrer"><img src={url} alt="Uploaded attachment" className="h-20 w-20 rounded-xl border bg-slate-100 object-cover"/></a><button type="button" onClick={()=>remove(index)} className="absolute -right-2 -top-2 grid h-6 w-6 place-items-center rounded-full bg-rose-600 text-xs font-black text-white">×</button></div>)}</div>}<textarea rows="2" value={value} onChange={e=>onChange(e.target.value)} placeholder="Uploaded file URLs appear here; you may also paste one URL per line." className="w-full rounded-xl border border-slate-200 px-3 py-2 text-xs"/></div>}
function TabGuide({tab}){const steps=GUIDES[tab]||[];return <details open className="mb-5 overflow-hidden rounded-2xl border border-indigo-200 bg-white shadow-sm"><summary className="cursor-pointer bg-gradient-to-r from-indigo-50 to-fuchsia-50 px-5 py-3 text-sm font-black text-indigo-950">How to use this tab · Features and next step</summary><div className="grid gap-3 p-5 md:grid-cols-3">{steps.map((step,index)=><div key={step} className="flex gap-3 rounded-xl bg-slate-50 p-3 text-sm leading-6 text-slate-600"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-violet-600 text-xs font-black text-white">{index+1}</span><p>{step}</p></div>)}</div></details>}

export default function DesignPattern(){
  const [active,setActive]=useState("dashboard"), [data,setData]=useState({projects:[],patterns:[],samples:[],queries:[],research:[],artworks:[],change_requests:[],tech_packs:[],material_plans:[]});
  const [loading,setLoading]=useState(true), [error,setError]=useState(""), [notice,setNotice]=useState(""), [modal,setModal]=useState(""), [search,setSearch]=useState("");
  const [settings,setSettings]=useState(null);
  const [projectForm,setProjectForm]=useState(emptyProject), [patternForm,setPatternForm]=useState(emptyPattern), [sampleForm,setSampleForm]=useState(emptySample), [queryForm,setQueryForm]=useState(emptyQuery), [releaseForm,setReleaseForm]=useState({project_id:"",tech_pack_id:"",material_plan_id:""});
  const [researchForm,setResearchForm]=useState(emptyResearch), [artworkForm,setArtworkForm]=useState(emptyArtwork), [changeForm,setChangeForm]=useState(emptyChange);
  const [floorDepts,setFloorDepts]=useState(DEFAULT_FLOOR_DEPARTMENTS), [floorWorkers,setFloorWorkers]=useState([]), [floorLogs,setFloorLogs]=useState([]), [floorKpis,setFloorKpis]=useState(null);
  const [floorSection,setFloorSection]=useState("log"), [floorLoaded,setFloorLoaded]=useState(false);
  const [floorFilters,setFloorFilters]=useState({date_from:"",date_to:"",department:"",worker_id:"",design_no:""});
  const [floorLogForm,setFloorLogForm]=useState(emptyFloorLog()), [floorWorkerForm,setFloorWorkerForm]=useState(emptyFloorWorker);
  const load=useCallback(async()=>{ setLoading(true);setError("");try{const [workspace,insights]=await Promise.all([api("/workspace"),api("/insights")]);setData({...workspace,insights:insights.data||[]});api("/settings").then(r=>setSettings(r.data)).catch(()=>setSettings(DEFAULT_SETTINGS));}catch(e){setError(e.message);}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  const run=async(path,payload,message)=>{try{const result=await api(path,{method:"POST",body:JSON.stringify(payload)});setNotice(result.message||message);setModal("");await load();}catch(e){setError(e.message);}};
  const loadFloorOps=useCallback(async()=>{try{const [depts,workers]=await Promise.all([api("/floor-departments"),api("/floor-workers")]);setFloorDepts(depts.data?.length?depts.data:DEFAULT_FLOOR_DEPARTMENTS);setFloorWorkers(workers.data||[]);}catch(e){setError(e.message);}},[]);
  const loadFloorLogs=useCallback(async(filters)=>{try{const q=new URLSearchParams(Object.entries(filters||{}).filter(([,v])=>v));const [logs,kpis]=await Promise.all([api(`/floor-logs?${q}`),api(`/floor-kpis?date_from=${filters?.date_from||""}&date_to=${filters?.date_to||""}`)]);setFloorLogs(logs.data||[]);setFloorKpis(kpis);}catch(e){setError(e.message);}},[]);
  useEffect(()=>{if(active==="floorops"&&!floorLoaded){setFloorLoaded(true);loadFloorOps();loadFloorLogs(floorFilters);}},[active,floorLoaded,loadFloorOps,loadFloorLogs,floorFilters]);
  const applyFloorFilters=()=>loadFloorLogs(floorFilters);
  const currentFloorDept=floorDepts.find(d=>d.name===floorLogForm.department);
  const currentFloorFields=currentFloorDept?.fields||[];
  const submitFloorLog=async(e)=>{e.preventDefault();try{await api("/floor-logs",{method:"POST",body:JSON.stringify(floorLogForm)});setNotice("Floor log entry saved.");setModal("");setFloorLogForm(emptyFloorLog());await loadFloorLogs(floorFilters);}catch(e2){setError(e2.message);}};
  const submitFloorWorker=async(e)=>{e.preventDefault();try{const result=await api("/floor-workers",{method:"POST",body:JSON.stringify(floorWorkerForm)});setNotice(result.message||"Worker added.");setModal("");setFloorWorkerForm(emptyFloorWorker);await loadFloorOps();}catch(e2){setError(e2.message);}};
  const toggleFloorWorker=async(w)=>{try{await api(`/floor-workers/${w.id}`,{method:"PATCH",body:JSON.stringify({active:!w.active})});await loadFloorOps();}catch(e2){setError(e2.message);}};
  const projects=useMemo(()=>data.projects.filter(p=>`${p.design_no} ${p.style_name} ${p.collection} ${p.designer}`.toLowerCase().includes(search.toLowerCase())),[data.projects,search]);
  const projectName=(id)=>{const p=data.projects.find(x=>x.id===id);return p?`${p.design_no} · ${p.style_name}`:"Unknown design";};
  const approvedSamples=new Set(data.samples.filter(s=>["APPROVED","APPROVED_WITH_COMMENTS"].includes(s.decision)).map(s=>s.project_id));
  const stats={active:data.projects.filter(p=>!["RELEASED_TO_PRODUCTION","ARCHIVED","REJECTED"].includes(p.status)).length,patterns:data.patterns.length,pending:data.samples.filter(s=>s.decision==="PENDING").length,approved:data.projects.filter(p=>p.status==="RELEASED_TO_PRODUCTION").length,queries:data.queries.filter(q=>!["RESOLVED","CLOSED"].includes(q.status)).length};
  const cfg = settings || DEFAULT_SETTINGS;
  const deptOptions = cfg.departments?.length ? cfg.departments : DEPARTMENTS;
  const sampleTypeOptions = cfg.sample_types?.length ? cfg.sample_types : DEFAULT_SETTINGS.sample_types;
  const startPattern=(id="")=>{setPatternForm({...emptyPattern,project_id:id,base_size:cfg.default_base_size||emptyPattern.base_size,sizes:cfg.default_size_run||emptyPattern.sizes,wastage_pct:String(cfg.default_wastage_pct ?? emptyPattern.wastage_pct)});setModal("pattern");};
  const openFor=(kind,id)=>{if(kind==="pattern")return startPattern(id);if(kind==="sample")setSampleForm({...emptySample,project_id:id,sample_type:sampleTypeOptions[1]||sampleTypeOptions[0]});if(kind==="query")setQueryForm({...emptyQuery,project_id:id});setModal(kind);};
  const updateStatus=async(project,status)=>{try{await api(`/projects/${project.id}`,{method:"PATCH",body:JSON.stringify({status})});setNotice(`${project.design_no} updated.`);await load();}catch(e){setError(e.message);}};

  const activeTab = active==="settings" ? ["settings","Settings"] : (TABS.find(([id])=>id===active) || TABS[0]);
  const adminName = getAdminName() || "Design user";
  const workspaceName = getAdminScope()==="hq" ? "Head office workspace" : (getStoreName() || "Store workspace");

  return <div className="dp-workspace flex">
    <style>{DP_UI_STYLES}</style>
    <aside className="dp-sidebar sticky top-0 flex h-screen shrink-0 flex-col p-4 text-white">
      <div className="dp-brand rounded-2xl p-4">
        <div className="flex items-center gap-3">
          <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-fuchsia-300 to-violet-500 text-sm font-black text-slate-950 shadow-lg shadow-fuchsia-950/20">D&amp;P</div>
          <div className="dp-brand-copy min-w-0">
            <p className="text-[11px] font-semibold uppercase tracking-[.18em] text-fuchsia-200">RMS product dev</p>
            <h1 className="truncate text-lg font-bold">Design &amp; Pattern</h1>
          </div>
        </div>
        <div className="dp-sidebar-note mt-4 rounded-xl border border-white/10 bg-slate-950/20 px-3 py-2.5">
          <p className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-300">Signed in as</p>
          <p className="mt-1 truncate text-sm font-semibold">{adminName}</p>
          <p className="mt-0.5 truncate text-xs text-fuchsia-100/75">{workspaceName}</p>
        </div>
      </div>
      <nav className="mt-6 flex-1 space-y-1 overflow-y-auto pr-1">
        <p className="dp-sidebar-note px-3 pb-2 text-[10px] font-bold uppercase tracking-[.18em] text-slate-400">Workflow</p>
        {TABS.map(([id,label,TabIcon])=><button key={id} onClick={()=>setActive(id)} title={label} className={`dp-nav-item flex w-full items-center rounded-xl px-3.5 py-2.5 text-left text-sm font-semibold transition-all ${active===id?"dp-nav-item-active":""}`}>{React.createElement(TabIcon,{className:"mr-3 h-[18px] w-[18px] shrink-0"})}<span className="dp-nav-label truncate">{label}</span></button>)}
      </nav>
      <div className="mt-3 border-t border-white/10 pt-3">
        <button onClick={()=>logoutOrReturnToDepartmentSelector()} className="flex w-full items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 py-2.5 text-sm font-bold text-slate-100 transition hover:bg-rose-500/20 hover:text-white"><X className="h-4 w-4"/><span className="dp-nav-label">Log out</span></button>
      </div>
    </aside>
    <main className="dp-content min-h-screen flex-1">
      <header className="dp-header sticky top-0 z-20 flex min-h-[88px] items-center justify-between gap-4 px-5 py-4 lg:px-9">
        <div className="min-w-0">
          <div className="mb-1 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.16em] text-fuchsia-700"><span>Design &amp; Pattern</span><span className="h-1 w-1 rounded-full bg-fuchsia-500"/><span>Product development</span></div>
          <h2 className="truncate text-2xl font-bold tracking-tight text-slate-900">{activeTab[1]}</h2>
          <p className="mt-0.5 hidden text-sm text-slate-500 sm:block">{SUBTITLES[active]}</p>
        </div>
        <div className="flex shrink-0 items-center gap-2">
          <button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-fuchsia-200 bg-fuchsia-50 px-4 py-2.5 text-sm font-bold text-fuchsia-700 transition hover:bg-fuchsia-100"><RefreshCw className="h-4 w-4"/><span className="hidden sm:inline">Refresh</span></button>
          <button onClick={()=>setActive("settings")} title="Settings" aria-label="Settings" className={`inline-flex h-[42px] w-[42px] items-center justify-center rounded-xl border transition ${active==="settings"?"border-fuchsia-300 bg-fuchsia-100 text-fuchsia-700":"border-fuchsia-200 bg-fuchsia-50 text-fuchsia-700 hover:bg-fuchsia-100"}`}><Settings className="h-4 w-4"/></button>
        </div>
      </header>
      <div className="mx-auto w-full max-w-[1540px] p-4 sm:p-6 lg:p-9">
        {notice&&<div className="mb-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-bold text-emerald-800">✓ {notice}</div>}{error&&<div className="mb-4 flex gap-2 rounded-2xl border border-rose-200 bg-rose-50 p-3 text-sm font-bold text-rose-800"><AlertCircle className="h-5 w-5 shrink-0"/>{error}</div>}
      {GUIDES[active]&&<TabGuide tab={active}/>}
      {active==="settings"&&<SettingsPanel key={settings?"ready":"loading"} settings={settings} onSaved={(d,m)=>{setSettings(d);setNotice(m||"Settings saved.");setError("");}} onError={setError}/>}
      {active!=="settings"&&(loading?<div className="p-20 text-center text-slate-400">Loading Design & Pattern workspace…</div>:<>
        {active==="dashboard"&&<div className="space-y-6"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Active designs",stats.active,"bg-violet-600"],["Pattern versions",stats.patterns,"bg-cyan-600"],["Samples pending",stats.pending,"bg-amber-500"],["Released",stats.approved,"bg-emerald-600"],["Open queries",stats.queries,"bg-rose-500"]].map(([l,v,c])=><article key={l} className="rounded-2xl border border-white bg-white/90 p-5 shadow-lg"><span className={`block h-1.5 w-10 rounded-full ${c}`}/><p className="mt-4 text-sm font-bold text-slate-500">{l}</p><p className="mt-1 text-3xl font-black text-slate-900">{v}</p></article>)}</section><section className="rounded-3xl border bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Production readiness</h2><p className="text-sm text-slate-500">A design needs an approved sample and matching tech pack before release.</p></div><button onClick={()=>{setProjectForm(emptyProject);setModal("project");}} className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-bold text-white">+ New design</button></div><div className="mt-5 space-y-3">{data.projects.slice(0,6).map(p=><div key={p.id} className="flex flex-col justify-between gap-3 rounded-2xl border p-4 sm:flex-row sm:items-center"><div><p className="font-black">{p.design_no} · {p.style_name}</p><p className="text-xs text-slate-500">{p.department||"No department"} · {p.collection||"No collection"}</p></div><div className="flex items-center gap-2"><span className={`text-xs font-bold ${approvedSamples.has(p.id)?"text-emerald-600":"text-amber-600"}`}>{approvedSamples.has(p.id)?"Sample approved":"Sample approval needed"}</span><Badge value={p.status}/></div></div>)}</div></section></div>}
        {active==="research"&&<Panel title="Research & Mood Boards" subtitle="Store season, market, trend and visual references that can be used in design projects." action={()=>{setResearchForm(emptyResearch);setModal("research");}} actionText="+ Add research">{data.research.length?data.research.map(r=><Card key={r.id} title={r.title} meta={`${r.category||"Research"} · ${r.season||"No season"} · ${r.department||"All departments"}`}><p className="text-sm text-slate-600">{r.notes||"No notes"}</p><AttachmentGallery urls={r.reference_urls} label="Research reference"/><p className="text-xs text-violet-600">{r.tags?.join(" · ")}{r.reference_urls?.length?` · ${r.reference_urls.length} reference(s)`:""}</p></Card>):<Empty>No research references yet.</Empty>}</Panel>}
        {active==="projects"&&<section className="rounded-3xl border bg-white shadow-xl"><div className="flex flex-col justify-between gap-3 border-b p-5 sm:flex-row sm:items-center"><div><h2 className="text-xl font-black">Design Projects</h2><p className="text-sm text-slate-500">One traceable record from idea to production release.</p></div><div className="flex gap-2"><label className="flex items-center gap-2 rounded-xl border px-3"><Search className="h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search designs" className="w-40 py-2.5 text-sm outline-none"/></label><button onClick={()=>{setProjectForm(emptyProject);setModal("project");}} className="rounded-xl bg-violet-600 px-4 text-sm font-bold text-white">+ New project</button></div></div><div className="divide-y">{projects.length?projects.map(p=><article key={p.id} className="p-5"><div className="flex flex-col justify-between gap-4 lg:flex-row"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-black text-slate-900">{p.design_no} · {p.style_name}</h3><Badge value={p.status}/><span className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-bold">{p.priority}</span></div><p className="mt-1 text-sm text-slate-500">{[p.department,p.category,p.collection,p.season,p.designer].filter(Boolean).join(" · ")}</p><p className="mt-2 max-w-3xl text-sm text-slate-600">{p.description||"No design brief entered."}</p><AttachmentGallery urls={[...(p.moodboard_urls||[]),...(p.document_urls||[])]} label="Design reference"/></div><div className="flex flex-wrap gap-2 lg:justify-end"><button onClick={()=>openFor("pattern",p.id)} className="rounded-xl border px-3 py-2 text-xs font-bold">Add pattern</button><button onClick={()=>openFor("sample",p.id)} className="rounded-xl border px-3 py-2 text-xs font-bold">Review sample</button><button onClick={()=>openFor("query",p.id)} className="rounded-xl border px-3 py-2 text-xs font-bold">Raise query</button><select value={p.status} onChange={e=>updateStatus(p,e.target.value)} className="rounded-xl border px-3 py-2 text-xs font-bold">{PROJECT_STATUSES.map(s=><option key={s}>{s}</option>)}</select></div></div></article>):<Empty>Create the first real design project.</Empty>}</div></section>}
        {active==="patterns"&&<Panel title="Pattern Versions" subtitle="Controlled pattern, grading and consumption records." action={()=>startPattern()} actionText="+ Add pattern">{data.patterns.length?data.patterns.map(p=><Card key={p.id} title={`${p.pattern_no} · ${p.pattern_name||"Pattern"}`} meta={`${projectName(p.project_id)} · ${p.version} · Base ${p.base_size||"—"}`}><p className="text-xs text-slate-500">Sizes: {p.sizes?.join(", ")||"Not set"} · {p.measurement_rows?.length||0} graded points · Consumption: {p.consumption_per_unit||0} · Wastage: {p.wastage_pct||0}%</p><div className="flex gap-2"><Badge value={p.status}/><button onClick={async()=>{const version=window.prompt("New version",`v${(Number(String(p.version).replace(/\D/g,""))||1)+1}`);if(!version)return;const reason=window.prompt("Revision reason")||"Technical revision";await run(`/patterns/${p.id}/revision`,{version,reason});}} className="rounded-lg border px-2 py-1 text-xs font-bold">Create revision</button></div></Card>):<Empty>No pattern versions yet.</Empty>}</Panel>}
        {active==="artwork"&&<Panel title="Print & Artwork Library" subtitle="Versioned print, embroidery and placement references linked to designs." action={()=>{setArtworkForm(emptyArtwork);setModal("artwork");}} actionText="+ Add artwork">{data.artworks.length?data.artworks.map(a=><Card key={a.id} title={`${a.artwork_no} · ${a.name}`} meta={`${projectName(a.project_id)} · ${a.kind} · ${a.version}`}><p className="text-xs text-slate-500">{[a.width&&`${a.width} wide`,a.height&&`${a.height} high`,a.placement,a.technique].filter(Boolean).join(" · ")}</p><AttachmentGallery urls={a.file_urls} label="Artwork"/><Badge value={a.status}/></Card>):<Empty>No print or artwork records yet.</Empty>}</Panel>}
        {active==="samples"&&<Panel title="Samples & Approval" subtitle="Record every sample round and the decision that gates Production." action={()=>{setSampleForm({...emptySample,sample_type:sampleTypeOptions[1]||sampleTypeOptions[0]});setModal("sample");}} actionText="+ Review sample">{data.samples.length?data.samples.map(s=><Card key={s.id} title={`${s.sample_no} · ${s.sample_type}`} meta={`${projectName(s.project_id)} · Qty ${s.quantity}`}><p className="text-sm text-slate-600">{s.review_notes||s.fit_result||"No review notes."}</p><AttachmentGallery urls={s.image_urls} label="Sample photo"/><Badge value={s.decision}/></Card>):<Empty>No sample reviews yet.</Empty>}</Panel>}
        {active==="techpacks"&&<><div className="mb-4 rounded-2xl border border-fuchsia-200 bg-fuchsia-50 p-4 text-sm text-fuchsia-900"><b>Shared with Production:</b> tech packs created here are the same records visible in Production & Job Work. Use the exact project design number, approve a sample, then release it from Production Handoff.</div><TechPackLibrary plans={data.material_plans||[]} onSelectForOrder={()=>{setActive("handoff");setNotice("Tech pack ready. Select its design project below to release it.");}}/></>}
        {active==="handoff"&&<Panel title="Approval & Production Handoff" subtitle="Requires approved sample, Design Head sign-off, Production feasibility, and a matching Tech Pack.">{data.projects.length?data.projects.map(p=>{const packs=data.tech_packs.filter(t=>t.design_no===p.design_no);const approvals=Object.fromEntries((p.approvals||[]).map(a=>[a.type,a.decision]));const ready=approvedSamples.has(p.id)&&packs.length&&approvals.DESIGN_HEAD==="APPROVED"&&approvals.PRODUCTION_FEASIBILITY==="APPROVED";return <Card key={p.id} title={`${p.design_no} · ${p.style_name}`} meta={`${packs.length} tech pack(s) · Sample ${approvedSamples.has(p.id)?"approved":"missing"}`}><AttachmentGallery urls={[...(p.moodboard_urls||[]),...packs.flatMap(t=>[...(t.sketch_urls||[]),...(t.detail_images||[]),...(t.artwork_urls||[]),...(t.trim_images||[]),...(t.colourway_images||[])])]} label="Handoff preview"/><div className="flex flex-wrap items-center gap-2"><Badge value={p.status}/><Badge value={`Design: ${approvals.DESIGN_HEAD||"PENDING"}`}/><Badge value={`Production: ${approvals.PRODUCTION_FEASIBILITY||"PENDING"}`}/>{approvals.DESIGN_HEAD!=="APPROVED"&&<button onClick={async()=>{const note=window.prompt("Design approval note")||"Approved for production review";try{await api(`/projects/${p.id}/approval`,{method:"POST",body:JSON.stringify({approval_type:"DESIGN_HEAD",decision:"APPROVED",note})});await load();}catch(e){setError(e.message);}}} className="rounded-xl border border-violet-200 px-3 py-2 text-xs font-bold text-violet-700">Design Head approve</button>}{p.status!=="RELEASED_TO_PRODUCTION"&&<button disabled={!ready} onClick={()=>{setReleaseForm({project_id:p.id,tech_pack_id:packs[0]?.id||"",material_plan_id:p.material_plan_id||""});setModal("release");}} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-40"><Send className="mr-1 inline h-3.5 w-3.5"/>Release to Production</button>}</div></Card>}):<Empty>Create a design project first.</Empty>}</Panel>}
        {active==="floorops"&&<FloorOpsView section={floorSection} setSection={setFloorSection} depts={floorDepts} workers={floorWorkers} logs={floorLogs} kpis={floorKpis} filters={floorFilters} setFilters={setFloorFilters} onApplyFilters={applyFloorFilters} onAddLog={()=>{setFloorLogForm(emptyFloorLog());setModal("floorlog");}} onAddWorker={()=>{setFloorWorkerForm(emptyFloorWorker);setModal("floorworker");}} onToggleWorker={toggleFloorWorker}/>}
        {active==="queries"&&<Panel title="Design & Production Queries" subtitle="Keep technical clarifications and revisions attached to the design." action={()=>setModal("query")} actionText="+ Raise query">{data.queries.length?data.queries.map(q=><Card key={q.id} title={`${q.query_no} · ${q.category}`} meta={`${projectName(q.project_id)} · ${q.priority}`}><p className="text-sm text-slate-600">{q.description}</p><AttachmentGallery urls={q.attachment_urls} label="Query attachment"/>{q.response&&<p className="rounded-lg bg-emerald-50 p-2 text-xs text-emerald-800"><b>Response:</b> {q.response}</p>}<div className="flex gap-2"><Badge value={q.status}/>{!["RESOLVED","CLOSED"].includes(q.status)&&<button onClick={async()=>{const response=window.prompt("Resolution / clarification");if(!response)return;try{await api(`/queries/${q.id}`,{method:"PATCH",body:JSON.stringify({status:"RESOLVED",response})});await load();}catch(e){setError(e.message);}}} className="rounded-lg border border-emerald-200 px-2 py-1 text-xs font-bold text-emerald-700">Resolve</button>}</div></Card>):<Empty>No open design or production queries.</Empty>}</Panel>}
        {active==="changes"&&<Panel title="Post-release Change Control" subtitle="Record specification changes and their material, cost and delivery impact." action={()=>{setChangeForm(emptyChange);setModal("change");}} actionText="+ Change request">{data.change_requests.length?data.change_requests.map(c=><Card key={c.id} title={`${c.change_no} · ${projectName(c.project_id)}`} meta={`Raised by ${c.raised_by||"Unknown"}`}><p className="text-sm text-slate-600">{c.reason}</p><p className="text-xs text-slate-500">Material: {c.material_impact||"None"} · Cost: {c.cost_impact||"None"} · Delivery: {c.delivery_impact||"None"}</p><div className="grid gap-3 sm:grid-cols-2"><div><p className="mb-1 text-[10px] font-black uppercase text-slate-400">Before</p><AttachmentGallery urls={c.before_urls} label="Before change"/></div><div><p className="mb-1 text-[10px] font-black uppercase text-slate-400">Proposed</p><AttachmentGallery urls={c.after_urls} label="Proposed change"/></div></div><Badge value={c.status}/></Card>):<Empty>No formal change requests.</Empty>}</Panel>}
        {active==="reports"&&<Reports data={data} projectName={projectName}/>}
      </>)}
      </div>
    </main>
    {modal==="project"&&<FormModal title="Create design project" onClose={()=>setModal("")} onSubmit={e=>{e.preventDefault();run("/projects",{...projectForm,moodboard_urls:projectForm.moodboard_urls.split("\n").filter(Boolean),document_urls:projectForm.document_urls.split("\n").filter(Boolean)})}}><div className="grid gap-4 md:grid-cols-2"><Field label="Design no. (auto if blank)"><input value={projectForm.design_no} onChange={e=>setProjectForm({...projectForm,design_no:e.target.value})}/></Field><Field label="Style name *"><input required value={projectForm.style_name} onChange={e=>setProjectForm({...projectForm,style_name:e.target.value})}/></Field><Field label="Department"><select value={projectForm.department} onChange={e=>setProjectForm({...projectForm,department:e.target.value})}>{deptOptions.map(x=><option key={x}>{x}</option>)}</select></Field>{["category","theme","collection","season","designer","target_customer"].map(k=><Field key={k} label={pretty(k)}><input value={projectForm[k]} onChange={e=>setProjectForm({...projectForm,[k]:e.target.value})}/></Field>)}<Field label="Planned quantity"><input type="number" min="0" value={projectForm.planned_quantity} onChange={e=>setProjectForm({...projectForm,planned_quantity:e.target.value})}/></Field><Field label="Target cost"><input type="number" min="0" value={projectForm.target_cost} onChange={e=>setProjectForm({...projectForm,target_cost:e.target.value})}/></Field><Field label="Launch date"><input type="date" value={projectForm.launch_date} onChange={e=>setProjectForm({...projectForm,launch_date:e.target.value})}/></Field><Field label="Priority"><select value={projectForm.priority} onChange={e=>setProjectForm({...projectForm,priority:e.target.value})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></select></Field><Field label="Design brief" wide><textarea rows="3" value={projectForm.description} onChange={e=>setProjectForm({...projectForm,description:e.target.value})}/></Field><AttachmentEditor label="Attach sketches, inspiration and mood-board images" value={projectForm.moodboard_urls} onChange={v=>setProjectForm({...projectForm,moodboard_urls:v})}/><AttachmentEditor label="Attach design documents" accept="image/*,.pdf,.doc,.docx" value={projectForm.document_urls} onChange={v=>setProjectForm({...projectForm,document_urls:v})}/></div></FormModal>}
    {modal==="pattern"&&<FormModal title="Add pattern version" onClose={()=>setModal("")} onSubmit={e=>{e.preventDefault();run("/patterns",{...patternForm,sizes:patternForm.sizes.split(",").map(x=>x.trim()).filter(Boolean),measurement_rows:gradingRows(patternForm.measurement_rows),file_urls:patternForm.file_urls.split("\n").filter(Boolean)})}}><div className="grid gap-4 md:grid-cols-2"><ProjectSelect value={patternForm.project_id} onChange={v=>setPatternForm({...patternForm,project_id:v})} projects={data.projects}/>{["pattern_no","pattern_name","version","base_size","sizes","fabric_width","consumption_per_unit","wastage_pct","marker_length","marker_efficiency","seam_allowance","shrinkage_allowance"].map(k=><Field key={k} label={pretty(k)}><input required={["pattern_name","version"].includes(k)} type={["consumption_per_unit","wastage_pct","marker_efficiency"].includes(k)?"number":"text"} value={patternForm[k]} onChange={e=>setPatternForm({...patternForm,[k]:e.target.value})}/></Field>)}<Field label="Measurement grading (Point | Base | S:36,M:38...)" wide><textarea rows="4" value={patternForm.measurement_rows} onChange={e=>setPatternForm({...patternForm,measurement_rows:e.target.value})} placeholder={'Chest | 40 | S:36, M:38, L:40, XL:42\nLength | 28 | S:27, M:28, L:29, XL:30'}/></Field><AssetUploader label="Upload CAD / DXF / PDF files" onUploaded={urls=>setPatternForm({...patternForm,file_urls:[patternForm.file_urls,...urls].filter(Boolean).join("\n")})}/><Field label="Technical file links" wide><textarea rows="2" value={patternForm.file_urls} onChange={e=>setPatternForm({...patternForm,file_urls:e.target.value})}/></Field><Field label="Pattern / grading notes" wide><textarea rows="3" value={patternForm.notes} onChange={e=>setPatternForm({...patternForm,notes:e.target.value})}/></Field></div></FormModal>}
    {modal==="sample"&&<FormModal title="Record sample request / review" onClose={()=>setModal("")} onSubmit={e=>{e.preventDefault();run("/samples",{...sampleForm,image_urls:sampleForm.image_urls.split("\n").filter(Boolean)})}}><div className="grid gap-4 md:grid-cols-2"><ProjectSelect value={sampleForm.project_id} onChange={v=>setSampleForm({...sampleForm,project_id:v})} projects={data.projects}/><Field label="Pattern version"><select value={sampleForm.pattern_id} onChange={e=>setSampleForm({...sampleForm,pattern_id:e.target.value})}><option value="">No pattern linked</option>{data.patterns.filter(p=>p.project_id===sampleForm.project_id).map(p=><option key={p.id} value={p.id}>{p.pattern_no} · {p.version}</option>)}</select></Field><Field label="Sample type"><select value={sampleForm.sample_type} onChange={e=>setSampleForm({...sampleForm,sample_type:e.target.value})}>{sampleTypeOptions.map(x=><option key={x}>{x}</option>)}</select></Field>{["quantity","required_date","received_date","assigned_to","estimated_cost","actual_cost"].map(k=><Field key={k} label={pretty(k)}><input type={k.includes("date")?"date":["quantity","estimated_cost","actual_cost"].includes(k)?"number":"text"} value={sampleForm[k]} onChange={e=>setSampleForm({...sampleForm,[k]:e.target.value})}/></Field>)}<Field label="Decision"><select value={sampleForm.decision} onChange={e=>setSampleForm({...sampleForm,decision:e.target.value})}>{DECISIONS.map(x=><option key={x}>{x}</option>)}</select></Field>{["materials","fit_result","construction_result"].map(k=><Field key={k} label={pretty(k)}><input value={sampleForm[k]} onChange={e=>setSampleForm({...sampleForm,[k]:e.target.value})}/></Field>)}<AttachmentEditor label="Attach front, back, side and fit-review photos" value={sampleForm.image_urls} onChange={v=>setSampleForm({...sampleForm,image_urls:v})}/><Field label="Review / correction notes" wide><textarea required rows="3" value={sampleForm.review_notes} onChange={e=>setSampleForm({...sampleForm,review_notes:e.target.value})}/></Field></div></FormModal>}
    {modal==="query"&&<FormModal title="Raise design query" onClose={()=>setModal("")} onSubmit={e=>{e.preventDefault();run("/queries",{...queryForm,attachment_urls:queryForm.attachment_urls.split("\n").filter(Boolean)})}}><div className="grid gap-4 md:grid-cols-2"><ProjectSelect value={queryForm.project_id} onChange={v=>setQueryForm({...queryForm,project_id:v})} projects={data.projects}/><Field label="Category"><select value={queryForm.category} onChange={e=>setQueryForm({...queryForm,category:e.target.value})}>{["Measurement clarification","Pattern file missing","Fabric specification","Artwork placement","Trim unavailable","Consumption concern","Construction feasibility","Other"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Priority"><select value={queryForm.priority} onChange={e=>setQueryForm({...queryForm,priority:e.target.value})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></select></Field><Field label="Question / issue" wide><textarea required rows="4" value={queryForm.description} onChange={e=>setQueryForm({...queryForm,description:e.target.value})}/></Field><AttachmentEditor label="Attach issue photos or screenshots" value={queryForm.attachment_urls} onChange={v=>setQueryForm({...queryForm,attachment_urls:v})}/></div></FormModal>}
    {modal==="release"&&<FormModal title="Release approved design to Production" onClose={()=>setModal("")} onSubmit={e=>{e.preventDefault();run(`/projects/${releaseForm.project_id}/release`,releaseForm)}}><div className="space-y-4"><div className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">This locks the selected Tech Pack as the Production reference. Active job orders retain their own snapshot.</div><Field label="Approved tech pack"><select required value={releaseForm.tech_pack_id} onChange={e=>setReleaseForm({...releaseForm,tech_pack_id:e.target.value})}>{data.tech_packs.filter(t=>t.design_no===data.projects.find(p=>p.id===releaseForm.project_id)?.design_no).map(t=><option key={t.id} value={t.id}>{t.tech_pack_no} · {t.version}</option>)}</select></Field><Field label="Style BOM / material plan"><select value={releaseForm.material_plan_id} onChange={e=>setReleaseForm({...releaseForm,material_plan_id:e.target.value,auto_create_bom:false})}><option value="">No existing BOM selected</option>{data.material_plans.map(p=><option key={p.id} value={p.id}>{p.plan_no} · {p.style_name}</option>)}</select></Field><label className="flex items-start gap-3 rounded-xl border p-3 text-sm"><input type="checkbox" checked={Boolean(releaseForm.auto_create_bom)} onChange={e=>setReleaseForm({...releaseForm,auto_create_bom:e.target.checked,material_plan_id:e.target.checked?"":releaseForm.material_plan_id})}/><span><b>Automatically create Style BOM</b><br/><span className="text-slate-500">Uses planned quantity and the latest pattern consumption/wastage.</span></span></label>{releaseForm.auto_create_bom&&<Field label="Main material name"><input value={releaseForm.material_name||""} onChange={e=>setReleaseForm({...releaseForm,material_name:e.target.value})} placeholder="Main fabric"/></Field>}</div></FormModal>}
    {modal==="research"&&<FormModal title="Add research reference" onClose={()=>setModal("")} onSubmit={e=>{e.preventDefault();run("/research",{...researchForm,tags:researchForm.tags.split(",").map(x=>x.trim()).filter(Boolean),reference_urls:researchForm.reference_urls.split("\n").filter(Boolean)})}}><div className="grid gap-4 md:grid-cols-2">{["title","category","season","market_segment"].map(k=><Field key={k} label={pretty(k)}><input required={k==="title"} value={researchForm[k]} onChange={e=>setResearchForm({...researchForm,[k]:e.target.value})}/></Field>)}<Field label="Department"><select value={researchForm.department} onChange={e=>setResearchForm({...researchForm,department:e.target.value})}>{deptOptions.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Tags (comma separated)"><input value={researchForm.tags} onChange={e=>setResearchForm({...researchForm,tags:e.target.value})}/></Field><AttachmentEditor label="Attach mood-board images and research documents" accept="image/*,.pdf" value={researchForm.reference_urls} onChange={v=>setResearchForm({...researchForm,reference_urls:v})}/><Field label="Research findings" wide><textarea rows="4" value={researchForm.notes} onChange={e=>setResearchForm({...researchForm,notes:e.target.value})}/></Field></div></FormModal>}
    {modal==="artwork"&&<FormModal title="Add print or artwork" onClose={()=>setModal("")} onSubmit={e=>{e.preventDefault();run("/artworks",{...artworkForm,file_urls:artworkForm.file_urls.split("\n").filter(Boolean)})}}><div className="grid gap-4 md:grid-cols-2"><ProjectSelect value={artworkForm.project_id} onChange={v=>setArtworkForm({...artworkForm,project_id:v})} projects={data.projects}/>{["name","kind","version","width","height","placement","technique","colours","status"].map(k=><Field key={k} label={pretty(k)}><input required={k==="name"} value={artworkForm[k]} onChange={e=>setArtworkForm({...artworkForm,[k]:e.target.value})}/></Field>)}<AttachmentEditor label="Attach artwork previews and source files" accept="image/*,.pdf,.ai,.psd,.cdr" value={artworkForm.file_urls} onChange={v=>setArtworkForm({...artworkForm,file_urls:v})}/><Field label="Instructions" wide><textarea rows="3" value={artworkForm.notes} onChange={e=>setArtworkForm({...artworkForm,notes:e.target.value})}/></Field></div></FormModal>}
    {modal==="change"&&<FormModal title="Create formal change request" onClose={()=>setModal("")} onSubmit={e=>{e.preventDefault();run("/change-requests",{...changeForm,before_urls:changeForm.before_urls.split("\n").filter(Boolean),after_urls:changeForm.after_urls.split("\n").filter(Boolean)})}}><div className="grid gap-4 md:grid-cols-2"><ProjectSelect value={changeForm.project_id} onChange={v=>setChangeForm({...changeForm,project_id:v})} projects={data.projects}/>{["reason","previous_spec","new_spec","material_impact","cost_impact","delivery_impact"].map(k=><Field key={k} label={pretty(k)} wide={["reason","previous_spec","new_spec"].includes(k)}><textarea required={["reason","previous_spec","new_spec"].includes(k)} rows="2" value={changeForm[k]} onChange={e=>setChangeForm({...changeForm,[k]:e.target.value})}/></Field>)}<AttachmentEditor label="Attach photos of the current specification" value={changeForm.before_urls} onChange={v=>setChangeForm({...changeForm,before_urls:v})}/><AttachmentEditor label="Attach marked-up or proposed revision images" value={changeForm.after_urls} onChange={v=>setChangeForm({...changeForm,after_urls:v})}/></div></FormModal>}
    {modal==="floorlog"&&<FormModal title="Log a floor entry" onClose={()=>setModal("")} onSubmit={submitFloorLog}>
      <div className="mb-4 rounded-xl bg-violet-50 p-3 text-xs text-violet-900">Floor workers have no login — fill this in on their behalf. Pick a name from the directory, or type a walk-in's name below.</div>
      <div className="grid gap-4 md:grid-cols-2">
        <Field label="Date"><input type="date" required value={floorLogForm.date} onChange={e=>setFloorLogForm({...floorLogForm,date:e.target.value})}/></Field>
        <Field label="Time"><input type="time" value={floorLogForm.time} onChange={e=>setFloorLogForm({...floorLogForm,time:e.target.value})}/></Field>
        <Field label="Department *"><select required value={floorLogForm.department} onChange={e=>setFloorLogForm({...floorLogForm,department:e.target.value})}><option value="">Select department</option>{floorDepts.map(d=><option key={d.name} value={d.name}>{d.name}</option>)}</select></Field>
        <Field label="Worker (from directory)"><select value={floorLogForm.worker_id} onChange={e=>{const w=floorWorkers.find(x=>x.id===e.target.value);setFloorLogForm({...floorLogForm,worker_id:e.target.value,worker_name:w?w.name:floorLogForm.worker_name});}}><option value="">— Not in directory, type below —</option>{floorWorkers.filter(w=>w.active!==false).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></Field>
        <Field label="Worker name *"><input required value={floorLogForm.worker_name} onChange={e=>setFloorLogForm({...floorLogForm,worker_name:e.target.value,worker_id:""})} placeholder="Full name"/></Field>
        <Field label="Style / Design no."><input list="dp-floor-design-list" value={floorLogForm.design_no} onChange={e=>setFloorLogForm({...floorLogForm,design_no:e.target.value})}/></Field>
        <Field label="Job Work Order # (blank for in-house staff)"><input value={floorLogForm.job_work_order_id} onChange={e=>setFloorLogForm({...floorLogForm,job_work_order_id:e.target.value})} placeholder="Only if this is a job worker's output"/></Field>
        {!currentFloorFields.length&&<p className="md:col-span-2 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-3 text-xs text-slate-500">Choose a department to see its fields.</p>}
        {currentFloorFields.map(key=>{
          const meta=FLOOR_FIELD_META[key]||{label:pretty(key),type:"text"};
          const label=currentFloorDept?.labels?.[key]||meta.label;
          if(key==="remarks") return <Field key={key} label={label} wide><textarea rows="2" value={floorLogForm.remarks} onChange={e=>setFloorLogForm({...floorLogForm,remarks:e.target.value})}/></Field>;
          if(key==="on_time") return <Field key={key} label={label}><select value={floorLogForm.on_time?"yes":"no"} onChange={e=>setFloorLogForm({...floorLogForm,on_time:e.target.value==="yes"})}><option value="yes">Yes</option><option value="no">No</option></select></Field>;
          if(meta.type==="number") return <Field key={key} label={label}><input type="number" min="0" step="0.01" value={floorLogForm[key]} onChange={e=>setFloorLogForm({...floorLogForm,[key]:e.target.value})}/></Field>;
          return <Field key={key} label={label}><input value={floorLogForm[key]} onChange={e=>setFloorLogForm({...floorLogForm,[key]:e.target.value})}/></Field>;
        })}
      </div>
      <datalist id="dp-floor-design-list">{data.projects.map(p=><option key={p.id} value={p.design_no}/>)}</datalist>
    </FormModal>}
    {modal==="floorworker"&&<FormModal title="Add floor worker" onClose={()=>setModal("")} onSubmit={submitFloorWorker}>
      <div className="grid gap-4 md:grid-cols-2">
        <Field label="Name *"><input required value={floorWorkerForm.name} onChange={e=>setFloorWorkerForm({...floorWorkerForm,name:e.target.value})}/></Field>
        <Field label="Phone (optional)"><input value={floorWorkerForm.phone} onChange={e=>setFloorWorkerForm({...floorWorkerForm,phone:e.target.value})}/></Field>
        <Field label="Departments this worker does" wide><div className="flex flex-wrap gap-2">{floorDepts.map(d=><label key={d.name} className="flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-2.5 py-1.5 text-xs font-bold text-slate-700"><input type="checkbox" checked={floorWorkerForm.departments.includes(d.name)} onChange={e=>setFloorWorkerForm({...floorWorkerForm,departments:e.target.checked?[...floorWorkerForm.departments,d.name]:floorWorkerForm.departments.filter(x=>x!==d.name)})}/>{d.name}</label>)}</div></Field>
        <Field label="Notes" wide><textarea rows="2" value={floorWorkerForm.notes} onChange={e=>setFloorWorkerForm({...floorWorkerForm,notes:e.target.value})}/></Field>
      </div>
    </FormModal>}
  </div>;
}

function SettingsPanel({settings,onSaved,onError}){
  const base=settings||DEFAULT_SETTINGS;
  const [section,setSection]=useState("workflow");
  const [form,setForm]=useState({
    departments:(base.departments||[]).join("\n"),
    sample_types:(base.sample_types||[]).join("\n"),
    default_base_size:base.default_base_size||"M",
    default_size_run:base.default_size_run||"S, M, L, XL",
    default_wastage_pct:String(base.default_wastage_pct??5),
  });
  const [saving,setSaving]=useState(false);
  const set=(key,value)=>setForm(current=>({...current,[key]:value}));
  const save=async()=>{
    setSaving(true);
    try{
      const payload={
        departments:form.departments.split("\n").map(value=>value.trim()).filter(Boolean),
        sample_types:form.sample_types.split("\n").map(value=>value.trim()).filter(Boolean),
        default_base_size:form.default_base_size.trim(),
        default_size_run:form.default_size_run.trim(),
        default_wastage_pct:Number(form.default_wastage_pct)||0,
      };
      const result=await api("/settings",{method:"PUT",body:JSON.stringify(payload)});
      onSaved(result.data,result.message);
    }catch(error){onError(error.message);}
    finally{setSaving(false);}
  };
  const box="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100";
  const labelClass="mb-1.5 block text-xs font-black uppercase tracking-wide text-slate-500";
  const sectionButton=(value)=>"rounded-xl px-4 py-2.5 text-sm font-bold transition "+(section===value?"bg-violet-600 text-white shadow-sm":"text-slate-600 hover:bg-slate-50");
  return <div className="space-y-5">
    <section className="overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-violet-950 to-fuchsia-800 p-6 text-white shadow-xl">
      <p className="text-xs font-extrabold uppercase tracking-[.18em] text-fuchsia-200">Design administration</p>
      <h2 className="mt-2 text-2xl font-black">Settings</h2>
      <p className="mt-2 max-w-3xl text-sm leading-6 text-violet-100">Manage Design & Pattern defaults here. Personal account and security controls use the same trusted settings shared by the other RMS departments.</p>
    </section>
    <nav className="flex flex-wrap gap-2 rounded-2xl border border-slate-200 bg-white p-2 shadow-sm" aria-label="Design settings sections">
      <button type="button" onClick={()=>setSection("workflow")} className={sectionButton("workflow")}>Design workflow</button>
      <button type="button" onClick={()=>setSection("account")} className={sectionButton("account")}>Account &amp; Security</button>
    </nav>
    {section==="account"?<AdminSettings departmentMode/>:<section className="max-w-4xl space-y-5 rounded-3xl border bg-white p-5 shadow-xl sm:p-6">
      <div><h3 className="text-xl font-black text-slate-900">Design workflow defaults</h3><p className="mt-1 text-sm text-slate-500">Control lists and starting values used in Design Projects, Research, Patterns and Sample Approval.</p></div>
      <div className="grid gap-4 rounded-2xl border border-violet-100 bg-violet-50/60 p-4 sm:grid-cols-3">
        <div><p className="text-xs font-black uppercase tracking-wide text-violet-500">Departments</p><p className="mt-1 text-2xl font-black text-violet-950">{form.departments.split("\n").filter(Boolean).length}</p></div>
        <div><p className="text-xs font-black uppercase tracking-wide text-violet-500">Sample stages</p><p className="mt-1 text-2xl font-black text-violet-950">{form.sample_types.split("\n").filter(Boolean).length}</p></div>
        <div><p className="text-xs font-black uppercase tracking-wide text-violet-500">Pattern default</p><p className="mt-1 text-sm font-black text-violet-950">{form.default_base_size||"—"} · {form.default_wastage_pct||0}% wastage</p></div>
      </div>
      <div className="grid gap-5 lg:grid-cols-2">
        <label className="block"><span className={labelClass}>Product departments <span className="font-semibold normal-case text-slate-400">— one per line</span></span><textarea rows="8" value={form.departments} onChange={event=>set("departments",event.target.value)} className={box}/><span className="mt-1 block text-xs text-slate-400">Used by Design Projects and Research &amp; Mood Boards.</span></label>
        <label className="block"><span className={labelClass}>Sample types <span className="font-semibold normal-case text-slate-400">— one per line</span></span><textarea rows="8" value={form.sample_types} onChange={event=>set("sample_types",event.target.value)} className={box}/><span className="mt-1 block text-xs text-slate-400">Used when recording sample requests and approvals.</span></label>
      </div>
      <div className="grid gap-4 sm:grid-cols-3">
        <label className="block"><span className={labelClass}>Default base size</span><input value={form.default_base_size} onChange={event=>set("default_base_size",event.target.value)} className={box}/></label>
        <label className="block"><span className={labelClass}>Default size run</span><input value={form.default_size_run} onChange={event=>set("default_size_run",event.target.value)} className={box}/></label>
        <label className="block"><span className={labelClass}>Default wastage %</span><input type="number" min="0" max="100" value={form.default_wastage_pct} onChange={event=>set("default_wastage_pct",event.target.value)} className={box}/></label>
      </div>
      <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>Safe default behavior:</b> these values prefill new records only. Existing projects, approved patterns and released production references are never rewritten.</div>
      <div className="flex justify-end border-t border-slate-100 pt-5"><button type="button" onClick={save} disabled={saving} className="rounded-xl bg-violet-600 px-6 py-2.5 text-sm font-bold text-white transition hover:bg-violet-700 disabled:opacity-50">{saving?"Saving…":"Save workflow defaults"}</button></div>
    </section>}
  </div>;
}
function Panel({title,subtitle,action,actionText,children}){return <section className="overflow-hidden rounded-3xl border bg-white shadow-xl"><header className="flex flex-col justify-between gap-3 border-b bg-gradient-to-r from-white to-violet-50 p-5 sm:flex-row sm:items-center"><div><h2 className="text-xl font-black">{title}</h2><p className="text-sm text-slate-500">{subtitle}</p></div>{action&&<button onClick={action} className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-bold text-white">{actionText}</button>}</header><div className="space-y-3 p-5">{children}</div></section>}
function Card({title,meta,children}){return <article className="flex flex-col justify-between gap-3 rounded-2xl border border-slate-200 p-4 lg:flex-row lg:items-center"><div><h3 className="font-black text-slate-900">{title}</h3><p className="mt-1 text-xs text-slate-500">{meta}</p></div><div className="flex max-w-2xl flex-col items-start gap-2 lg:items-end">{children}</div></article>}
function FormModal({title,onClose,onSubmit,children}){return <Modal title={title} onClose={onClose}><form onSubmit={onSubmit} className="p-4 sm:p-6">{children}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-xl border px-4 py-2.5 text-sm font-bold">Cancel</button><button className="rounded-xl bg-violet-600 px-5 py-2.5 text-sm font-bold text-white">Save</button></div></form></Modal>}
function ProjectSelect({value,onChange,projects}){return <Field label="Design project *"><select required value={value} onChange={e=>onChange(e.target.value)}><option value="">Select design</option>{projects.map(p=><option key={p.id} value={p.id}>{p.design_no} · {p.style_name}</option>)}</select></Field>}
function AssetUploader({label,onUploaded,accept="image/*"}){const [busy,setBusy]=useState(false),[message,setMessage]=useState("");const upload=async(files)=>{if(!files?.length)return;setBusy(true);setMessage("Uploading "+files.length+" file"+(files.length===1?"":"s")+"...");try{const body=new FormData();[...files].forEach(f=>body.append("files",f));const token=localStorage.getItem("admin_token")||localStorage.getItem("access_token")||localStorage.getItem("token")||"";const response=await fetch(API_BASE_URL+"/api/design-pattern/assets",{method:"POST",headers:token?{Authorization:"Bearer "+token}:{},body});const result=await response.json();if(!response.ok)throw new Error(result.detail||"Upload failed");onUploaded(result.data.map(x=>x.url));setMessage(result.data.length+" file"+(result.data.length===1?"":"s")+" uploaded successfully");}catch(e){setMessage(e.message);}finally{setBusy(false);}};const failed=message.toLowerCase().includes("failed")||message.toLowerCase().includes("error");return <div className="w-full min-w-0 md:col-span-2"><div className="w-full min-w-0 overflow-hidden rounded-2xl border border-dashed border-violet-300 bg-violet-50/70 p-4"><p className="break-words text-xs font-black uppercase tracking-wide text-violet-700">{label}</p><p className="mt-1 text-xs text-slate-500">Choose one or more files. They upload immediately and appear below.</p><input type="file" multiple accept={accept} onChange={e=>{upload(e.target.files);e.target.value="";}} className="mt-3 block w-full min-w-0 cursor-pointer overflow-hidden rounded-xl border border-violet-200 bg-white text-sm text-slate-600 file:mr-3 file:cursor-pointer file:border-0 file:bg-violet-600 file:px-4 file:py-2.5 file:text-sm file:font-bold file:text-white hover:file:bg-violet-700 disabled:cursor-wait disabled:opacity-60" disabled={busy}/>{message&&<p className={"mt-2 break-words text-xs font-semibold "+(failed?"text-rose-600":"text-slate-600")}>{message}</p>}</div></div>}
function Reports({data}){const byDesigner=Object.entries(data.projects.reduce((a,p)=>{const k=p.designer||"Unassigned";a[k]=(a[k]||0)+1;return a;},{}));const sampleCost=data.samples.reduce((s,x)=>s+Number(x.actual_cost||x.estimated_cost||0),0);const deadlines=[...data.projects.filter(p=>p.launch_date).map(p=>({date:p.launch_date,label:`Launch · ${p.design_no}`})),...data.samples.filter(s=>s.required_date&&s.decision==="PENDING").map(s=>({date:s.required_date,label:`Sample · ${s.design_no}`}))].sort((a,b)=>a.date.localeCompare(b.date));return <div className="space-y-5"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Designs",data.projects.length],["Release rate",`${data.projects.length?Math.round(data.projects.filter(p=>p.status==="RELEASED_TO_PRODUCTION").length/data.projects.length*100):0}%`],["Sample cost",`₹${sampleCost.toLocaleString("en-IN")}`],["Revisions",data.samples.filter(s=>s.decision?.includes("REVISION")||s.decision==="RESAMPLE_REQUIRED").length]].map(([l,v])=><article key={l} className="rounded-2xl border bg-white p-5 shadow"><p className="text-sm font-bold text-slate-500">{l}</p><p className="mt-1 text-3xl font-black">{v}</p></article>)}</section><div className="grid gap-5 xl:grid-cols-2"><Panel title="Designer workload" subtitle="Current project ownership.">{byDesigner.length?byDesigner.map(([name,count])=><div key={name} className="flex justify-between rounded-xl border p-3"><b>{name}</b><span>{count} project(s)</span></div>):<Empty>No workload data.</Empty>}</Panel><Panel title="Deadline calendar" subtitle="Upcoming sample and launch commitments.">{deadlines.length?deadlines.slice(0,12).map(x=><div key={`${x.date}${x.label}`} className="flex justify-between rounded-xl border p-3"><b>{x.label}</b><span>{x.date}</span></div>):<Empty>No dated commitments.</Empty>}</Panel></div><Panel title="Design cost & sales performance" subtitle="BOM material estimate, sampling cost and matched sales units.">{(data.insights||[]).length?(data.insights||[]).map(x=><div key={x.project_id} className="grid gap-2 rounded-xl border p-3 text-sm sm:grid-cols-5"><b>{x.design_no} · {x.style_name}</b><span>Target ₹{x.target_cost}</span><span>Material ₹{x.material_cost}</span><span>Samples ₹{x.sample_cost}</span><span className="font-bold text-emerald-700">Sales {x.sales_units} units</span></div>):<Empty>No linked costing or sales data.</Empty>}</Panel></div>}

function FloorOpsView({section,setSection,depts,workers,logs,kpis,filters,setFilters,onApplyFilters,onAddLog,onAddWorker,onToggleWorker}){
  const sectionBtn=(v)=>"rounded-xl px-4 py-2.5 text-sm font-bold transition "+(section===v?"bg-violet-600 text-white shadow-sm":"text-slate-600 hover:bg-slate-50");
  return <div className="space-y-5">
    <nav className="flex flex-wrap gap-2 rounded-2xl border border-slate-200 bg-white p-2 shadow-sm" aria-label="Floor operations sections">
      <button type="button" onClick={()=>setSection("log")} className={sectionBtn("log")}>Daily Log</button>
      <button type="button" onClick={()=>setSection("workers")} className={sectionBtn("workers")}>Floor Workers</button>
      <button type="button" onClick={()=>setSection("kpi")} className={sectionBtn("kpi")}>KPI Summary</button>
    </nav>
    {section==="log"&&<section className="overflow-hidden rounded-3xl border bg-white shadow-xl">
      <div className="flex flex-col justify-between gap-3 border-b p-5 sm:flex-row sm:items-center">
        <div><h2 className="text-xl font-black">Daily production log</h2><p className="text-sm text-slate-500">One entry per worker, per department, per day — including outsourced job workers.</p></div>
        <button onClick={onAddLog} className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-bold text-white">+ Log entry</button>
      </div>
      <div className="grid gap-3 border-b bg-slate-50 p-4 sm:grid-cols-5">
        <label className="block"><span className="mb-1 block text-[11px] font-black uppercase text-slate-500">From</span><input type="date" value={filters.date_from} onChange={e=>setFilters({...filters,date_from:e.target.value})} className="w-full rounded-lg border border-slate-200 px-2 py-1.5 text-sm"/></label>
        <label className="block"><span className="mb-1 block text-[11px] font-black uppercase text-slate-500">To</span><input type="date" value={filters.date_to} onChange={e=>setFilters({...filters,date_to:e.target.value})} className="w-full rounded-lg border border-slate-200 px-2 py-1.5 text-sm"/></label>
        <label className="block"><span className="mb-1 block text-[11px] font-black uppercase text-slate-500">Department</span><select value={filters.department} onChange={e=>setFilters({...filters,department:e.target.value})} className="w-full rounded-lg border border-slate-200 px-2 py-1.5 text-sm"><option value="">All</option>{depts.map(d=><option key={d.name} value={d.name}>{d.name}</option>)}</select></label>
        <label className="block"><span className="mb-1 block text-[11px] font-black uppercase text-slate-500">Style / Design no.</span><input value={filters.design_no} onChange={e=>setFilters({...filters,design_no:e.target.value})} className="w-full rounded-lg border border-slate-200 px-2 py-1.5 text-sm"/></label>
        <div className="flex items-end"><button onClick={onApplyFilters} className="w-full rounded-lg border border-violet-200 bg-violet-50 px-3 py-2 text-sm font-bold text-violet-700">Apply filters</button></div>
      </div>
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead className="bg-slate-50 text-left text-[11px] font-black uppercase text-slate-500"><tr>{["Date","Dept","Worker","Style","Target","Done","Rework","Rejected","Fabric(m)","Waste(m)","On-time","Remarks"].map(h=><th key={h} className="whitespace-nowrap px-3 py-2.5">{h}</th>)}</tr></thead>
          <tbody className="divide-y divide-slate-100">
            {logs.length?logs.map(l=><tr key={l.id}>
              <td className="whitespace-nowrap px-3 py-2.5 text-xs text-slate-500">{l.date}{l.time?` · ${l.time}`:""}</td>
              <td className="whitespace-nowrap px-3 py-2.5 text-xs font-bold text-slate-800">{l.department}</td>
              <td className="whitespace-nowrap px-3 py-2.5 text-xs text-slate-700">{l.worker_name}{l.source==="JOB_WORK"?<span className="ml-1.5 rounded-full bg-amber-100 px-1.5 py-0.5 text-[9px] font-bold text-amber-700">Job worker</span>:null}</td>
              <td className="whitespace-nowrap px-3 py-2.5 text-xs text-slate-600">{l.design_no||"—"}</td>
              <td className="px-3 py-2.5 text-xs">{l.target_qty||0}</td>
              <td className="px-3 py-2.5 text-xs font-bold text-slate-900">{l.completed_qty||0}</td>
              <td className="px-3 py-2.5 text-xs">{l.rework_qty||0}</td>
              <td className="px-3 py-2.5 text-xs text-rose-600">{l.rejected_qty||0}</td>
              <td className="px-3 py-2.5 text-xs">{l.fabric_used_mtrs||0}</td>
              <td className="px-3 py-2.5 text-xs">{l.wastage_mtrs||0}</td>
              <td className="px-3 py-2.5 text-xs">{l.on_time?"Yes":"No"}</td>
              <td className="max-w-[220px] truncate px-3 py-2.5 text-xs text-slate-500" title={l.remarks}>{l.remarks||"—"}</td>
            </tr>):<tr><td colSpan={12} className="p-10 text-center text-sm text-slate-400">No entries yet for this filter.</td></tr>}
          </tbody>
        </table>
      </div>
    </section>}
    {section==="workers"&&<section className="overflow-hidden rounded-3xl border bg-white shadow-xl">
      <div className="flex flex-col justify-between gap-3 border-b p-5 sm:flex-row sm:items-center">
        <div><h2 className="text-xl font-black">Floor worker directory</h2><p className="text-sm text-slate-500">Names only — no login or email needed. A worker can be tagged to more than one department.</p></div>
        <button onClick={onAddWorker} className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-bold text-white">+ Add worker</button>
      </div>
      <div className="divide-y divide-slate-100">
        {workers.length?workers.map(w=><div key={w.id} className="flex flex-col justify-between gap-3 p-4 sm:flex-row sm:items-center">
          <div><p className="font-black text-slate-900">{w.name}</p><p className="text-xs text-slate-500">{w.phone||"No phone on file"} · {(w.departments||[]).join(", ")||"No department set"}</p></div>
          <div className="flex items-center gap-2"><span className={`text-xs font-bold ${w.active!==false?"text-emerald-600":"text-slate-400"}`}>{w.active!==false?"Active":"Inactive"}</span><button onClick={()=>onToggleWorker(w)} className="rounded-lg border px-3 py-1.5 text-xs font-bold">{w.active!==false?"Deactivate":"Activate"}</button></div>
        </div>):<Empty>No floor workers added yet.</Empty>}
      </div>
    </section>}
    {section==="kpi"&&<div className="space-y-5">
      <div className="flex flex-wrap items-end gap-3 rounded-2xl border bg-white p-4 shadow-sm">
        <label className="block"><span className="mb-1 block text-[11px] font-black uppercase text-slate-500">From</span><input type="date" value={filters.date_from} onChange={e=>setFilters({...filters,date_from:e.target.value})} className="rounded-lg border border-slate-200 px-2 py-1.5 text-sm"/></label>
        <label className="block"><span className="mb-1 block text-[11px] font-black uppercase text-slate-500">To</span><input type="date" value={filters.date_to} onChange={e=>setFilters({...filters,date_to:e.target.value})} className="rounded-lg border border-slate-200 px-2 py-1.5 text-sm"/></label>
        <button onClick={onApplyFilters} className="rounded-lg border border-violet-200 bg-violet-50 px-4 py-2 text-sm font-bold text-violet-700">Refresh KPIs</button>
      </div>
      {kpis?.totals?<section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
        {[["Entries",kpis.entry_count],["Efficiency",kpis.totals.efficiency_pct!=null?`${kpis.totals.efficiency_pct}%`:"—"],["Rework",kpis.totals.rework_pct!=null?`${kpis.totals.rework_pct}%`:"—"],["Rejection",kpis.totals.rejection_pct!=null?`${kpis.totals.rejection_pct}%`:"—"],["On-time",kpis.totals.on_time_pct!=null?`${kpis.totals.on_time_pct}%`:"—"]].map(([l,v])=><article key={l} className="rounded-2xl border bg-white p-5 shadow"><p className="text-sm font-bold text-slate-500">{l}</p><p className="mt-1 text-3xl font-black">{v}</p></article>)}
      </section>:<Empty>No entries yet for this range.</Empty>}
      <div className="grid gap-5 xl:grid-cols-3">
        <KpiTable title="By department" rows={kpis?.by_department}/>
        <KpiTable title="By worker" rows={kpis?.by_worker}/>
        <KpiTable title="By style" rows={kpis?.by_design}/>
      </div>
    </div>}
  </div>;
}
function KpiTable({title,rows}){return <Panel title={title} subtitle="Efficiency = completed/target · rework & rejection = % of completed.">{rows?.length?rows.map(r=><div key={r.key} className="flex items-center justify-between gap-2 rounded-xl border p-3 text-sm"><b className="truncate">{r.key}</b><span className="shrink-0 text-xs font-bold text-slate-500">{r.entries} entr{r.entries===1?"y":"ies"} · Eff {r.efficiency_pct!=null?`${r.efficiency_pct}%`:"—"} · Rej {r.rejection_pct!=null?`${r.rejection_pct}%`:"—"}</span></div>):<Empty>No data.</Empty>}</Panel>}

