import { API_BASE_URL as APP_API_URL } from "../config/api.js";
import React, { useEffect, useRef, useState } from "react";
import { Bell, CheckCheck, RefreshCw, X } from "lucide-react";

const API_BASE=APP_API_URL;
export default function ProcurementNotificationCenter({mode="buyer",count=0,onCountChange=()=>{},onNavigate=()=>{}}){
 const [open,setOpen]=useState(false),[rows,setRows]=useState([]),[loading,setLoading]=useState(false),[unreadOnly,setUnreadOnly]=useState(false);const root=useRef(null);
 const token=()=>mode==="vendor"?localStorage.getItem("vendor_token"):(localStorage.getItem("admin_token")||localStorage.getItem("token"));
 const request=async(path,options={})=>fetch(`${API_BASE}/api/procurement-notifications/${mode}${path}`,{...options,headers:{Authorization:`Bearer ${token()}`,...(options.headers||{})}});
 const load=async()=>{setLoading(true);try{const r=await request("");const j=await r.json();if(r.ok)setRows(Array.isArray(j.data)?j.data:[])}finally{setLoading(false)}};
 useEffect(()=>{if(open)load()},[open]);
 useEffect(()=>{const close=e=>{if(root.current&&!root.current.contains(e.target))setOpen(false)};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[]);
 const markOne=async(row)=>{if(!row.read){await request(`/${row.id}/read`,{method:"POST"});setRows(old=>old.map(n=>n.id===row.id?{...n,read:true}:n));onCountChange(Math.max(0,count-1))}setOpen(false);onNavigate(row)};
 const markAll=async()=>{await request("/read",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({})});setRows(old=>old.map(n=>({...n,read:true})));onCountChange(0)};
 const visible=unreadOnly?rows.filter(r=>!r.read):rows;
 return <div ref={root} className="relative"><button type="button" onClick={()=>setOpen(v=>!v)} className="relative rounded-xl border border-slate-200 bg-white p-2.5 text-slate-600 shadow-sm hover:bg-slate-50" aria-label="Procurement notifications"><Bell size={18}/>{count>0&&<span className="absolute -right-1.5 -top-1.5 flex h-5 min-w-5 items-center justify-center rounded-full bg-rose-500 px-1 text-[9px] font-black text-white">{count>99?"99+":count}</span>}</button>{open&&<div className="absolute right-0 z-[2000] mt-2 w-[360px] max-w-[90vw] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-3"><div><p className="text-sm font-black text-slate-900">Procurement notifications</p><button onClick={()=>setUnreadOnly(v=>!v)} className="text-[10px] font-bold text-violet-600">{unreadOnly?"Show all":"Unread only"}</button></div><div className="flex gap-1"><button onClick={markAll} title="Mark all read" className="p-2 text-emerald-600"><CheckCheck size={16}/></button><button onClick={load} className="p-2 text-slate-500"><RefreshCw size={16} className={loading?"animate-spin":""}/></button><button onClick={()=>setOpen(false)} className="p-2 text-slate-500"><X size={16}/></button></div></div><div className="max-h-96 overflow-y-auto">{visible.map(row=><button key={row.id} onClick={()=>markOne(row)} className={`block w-full border-b border-slate-100 p-3 text-left hover:bg-slate-50 ${!row.read?"bg-violet-50/60":""}`}><div className="flex gap-2"><span className={`mt-1 h-2 w-2 shrink-0 rounded-full ${row.read?"bg-slate-200":"bg-violet-500"}`}/><div><p className="text-xs font-black text-slate-800">{row.title}</p><p className="mt-1 text-[11px] text-slate-500">{row.message}</p><p className="mt-1 text-[9px] text-slate-400">{row.created_at?new Date(row.created_at).toLocaleString():""}</p></div></div></button>)}{!visible.length&&!loading&&<p className="p-8 text-center text-xs text-slate-400">No notifications</p>}</div></div>}</div>;
}
